const lang = {
    EN: {
        API: {
            NO_UTXO_ERR: 'UTXO(s) no disponible o error de connexió',
            CANT_BROADCAST_TX_ERR: 'No es pot transmetre la transacció',
            BAD_TX_INPUTS_SPENT_ERR: "S'han emprat entrades de transacció incorrectes",
            CON_ERROR: 'Error de connexió. Si us plau reintenta.',
            NETWORK_ERROR_TITLE: 'Ups!',
            NETWORK_ERROR_MSG: 'Sembla que hi han alguns errors de connexió, si us plau assegura\'t que tens connexió a internet i torna-ho a intentar',
        },
        SETTINGS: {
            SAVED: 'Desat!',
            AUTOLOCK_TIMEOUT: 'Temps de espera per autobloqueig',
            MINUTES: 'minuts',
            SAVE: 'Desar',
            RECOVER: 'recuperar la contrassenya',
            RECOVER_PRIVATE_KEYS: 'RECUPERAR CLAUS PRIVADES',
            LOGOUT: 'desconnectar',
            REQUIRE_PIN_CONFIRM: 'Requerir PIN per confirmar la transacció',
            ACTIVATE_WALLETS_HINT: 'Selecciona els moneders que desitjis activar',
            COPIED_TO_CLIPBOARD: 'Copiat al porta-retalls',
            REQUIRE_PASSWORD_CONFIRM: 'Requereix contrassenya per confirmar transacció',
            AUTHORIZATION_METHOD: 'Mètode autorització',
            CHANGE_PASSWORD_HINT: 'Canvia contrassenya',
            CHANGE_PIN_HINT: 'Canvia PIN',
            CHANGE_LANGUAGE_HINT: 'Llengua',
            CHANGE_CURRENCY_HINT: 'Moneda preferida',
            REQUIRE_AUTH_CONFIRM: 'Requerir autorització per confirmar transaccions',
            DISCLAIMER_MSG_ABOUT: 'Note: all FIAT quantities are approximated using external price feed sources',
        },
        RECOVERY: {
            PROVIDE_YOUR_PIN: 'Introdueix el PIN per desbloquejar',
            PROVIDE_YOUR_PASSWORD: 'Introdueix la contrasenya per desbloquejar',
            PROVIDE_YOUR_PIN_KEYS: 'Introdueix el PIN per desbloquejar',
            PROVIDE_YOUR_PASSWORD_KEYS: 'Provide your password number to unlock private keys.',
            SHOW: 'Mostra',
            RECOVER_WALLET_HINT: 'Utilitza aquesta frase per recuperar el teu Pungo Wallet',
        },
        PIN: {
            SAVE: 'Desa',
            SEED_IS_ENCRYPTED: 'La llavor està encriptada amb el PIN proporcionat. Utilitza el PIN per ingressar o firmar una transacció.',
            PROVIDE_A_PASSPHRASE: 'Proporciona una frase segura',
            PROVIDE_A_SEED: 'Proporciona una frase segura i introdueix el número PIN de 6 dígits en el formulari inferior.',
        },
        OVERVIEW: {
            PRICES_ERROR: 'Proveïdor de preus inaccessible',
        },
        OFFLINE: {
            TX_SIG_FAIL: 'fallida al firmar la transacció',
            CONFIRM: 'Confirmar',
            TX_PIN_CONFIRM: 'Per confirmar la transacció proporciona el PIN y prem el botó de sota.',
            OFFLINE_TX_SIG: 'Firma transacció sense connexió',
            SEND_FROM: 'Enviar de',
            SEND_TO: 'Enviar a',
            AMOUNT: 'Import',
        },
        LOGIN: {
            OR_WIF: 'o WIF',
            CREATE_A_PIN: 'Crea un PIN',
            SIGN_IN_TO_YOUR_ACC: 'Entra al teu compte',
            SIGN_IN: 'Registrar-se',
            DONE: 'Fet',
            GENERATE: 'Generar',
            PASTE: 'Enganxar',
            PIN_ACCESS: 'Accés amb PIN',
            WRONG_PIN: 'PIN incorrecte!',
            LOGIN: 'Ingressar',
            PASSPHRASE_ACCESS: "Contrassenya d'accés",
            ENTER_PASSPHRASE: 'Introdueix una contrassenya',
            OVERRIDE_PIN: 'Crear / Substituir PIN',
            ENTER_6_DIGIT_PIN: 'Introdueix un PIN (min. 6 dígits)',
            ENTER_PIN: 'Introdueix un PIN',
            PIN_TOO_SHORT: 'El PIN és massa curt!',
            I_CONFIRM_I_SAVED_SEED: 'Confirmo que he desat la frase secreta',
            PLEASE_MAKE_SURE_TO: "Si us plau, assegura't d'anotar la frase secreta en un lloc segur!",
            THIS_IS_YOUR_NEW_SEED: 'Aquesta és la teva nova frase secreta',
            CREATE_RECOVER_WALLET: 'Crear / Recuperar Moneder',
            CONFIRMATION_REQUIRED: 'Es requereix confirmació',
            CREATE_WALLET: 'Crear moneder',
            RECOVER_WALLET: 'Recuperar moneder',
            PASSPHRASE_HINT: 'Enganxar una frase secreta existent',
            NEW_PIN_HINT: 'Introdueix un nou PIN per accedir al teu moneder',
            GENERATE_NEW_PASSPHRASE_HINT: 'Generar nova frase secreta',
            POPUP_WARNING_MSG: 'Avís',
            POPUP_WARNING_WIPE_WALLET: 'Si prosegueixes el teu actual moneder serà ESBORRAT. Estàs segur?',
            WIPE_WALLET_ACTION_YES: 'Sí',
            WIPE_WALLET_ACTION_NO: 'No',
            LOGIN_WITH_PIN_HINT: 'ingressar amb pin',
            SECURITY_ENCRYPTION_METHOD_PIN: 'PIN',
            SECURITY_ENCRYPTION_METHOD_PASSWORD: 'Contrassenya',
            SECURITY_ENCRYPTION_METHOD_HINT: 'Mètode de seguretat',
            ENTER_6_CHARS_PASSWORD: 'Introdueix una contrassenya (mín. 6 car)',
            PASSWORD_TOO_SHORT: 'Contrassenya massa curta!',
            NEW_PASSWORD_HINT: 'Introdueix una nova contrassenya per accedir al moneder',
            INTRODUCE_OLD_PIN_HINT: 'Introdueix PIN antic',
            INTRODUCE_NEW_PIN_HINT: 'Introdueix PIN nou',
            CONFIRM_NEW_PIN_HINT: 'Confirma nou PIN',
            INTRODUCE_OLD_PASSWORD_HINT: 'Introdueix contrassenya antiga',
            INTRODUCE_NEW_PASSWORD_HINT: 'Introdueix contrassenya nova',
            CONFIRM_NEW_PASSWORD_HINT: 'Confirma nova contrassenya',
            CONFIRM_HINT: 'Confirma',
            CANCEL_HINT: 'Cancela',
            PASSWORDS_DO_NOT_MATCH: 'Les contrassenyes no coincideixen',
            PINS_DO_NOT_MATCH: 'Els PINs no coincideixen',
            WRONG_PASSWORD: 'Contrassenya errònea!',
            ENTER_PASSWORD: 'Introdueix contrassenya',
            LOGIN_WITH_PASSWORD_HINT: 'accedeix amb contrassenya',
            PIN_CODES_DONT_MATCH_HINT: 'Els PIN no coincideixen',
            RE_ENTER_6_DIGIT_PIN: 'Reintrodueix el PIN',
            PASSWORDS_DONT_MATCH_HINT: 'Les contrassenyes no coincideixen',
            RE_ENTER_PASSWORD: 'Reintrodueix la contrassenya',
            OPEN_WALLET: 'Obre el moneder',
            WARNING_CREATE_WALLET_MSG: 'Crear un nou moneder generant una nova frase secreta',
            WARNING_RECOVER_WALLET_MSG: 'Recupera el teu moneder inserint la teva frase secreta',
            WARNING_MSG: 'ATENCIÓ',
            WARNING_WIPE_DATA_MSG: 'Si continues esborrarà totes les dades anteriors',
        },
        SEND: {
            TOTAL: 'Total',
            FEE: 'Comissió',
            BTC_FEE_SLOW: 'Lenta (60 min)',
            BTC_FEE_AVG: 'Mitja (30 min)',
            BTC_FEE_FAST: 'Ràpida (< 30 min)',
            BTC_FEES_FETCHING: 'Extraient dades de comissió btc...',
            BTC_FEES_FETCHING_FAILED: 'Fallida al recuperar dades de comissió btc. Reintentant en 5s...',
            SUCCESS: 'Fet',
            ENTER_YOUR_PIN: 'Entra el teu PIN',
            SEND: 'Enviar',
            NEXT: 'Següent',
            BACK: 'Enrere',
            SEND_FROM: 'Enviar desde',
            SEND_TO: 'Enviar a',
            SEND_ALL: 'Enviar tot',
            ENTER_AN_ADDRESS: 'Introdueix adreça',
            AMOUNT: 'Import',
            FILL_IN_DETAILS: 'Omple els detalls',
            CONFIRM: 'Confirmar',
            TO: 'Destinatari',
            WALLET_BALANCE: 'Saldo moneder',
            FROM: 'Enviant de',
            BALANCE: 'Saldo',
            WARNING: 'Avís',
            WARNING_SPV_P1: 'Les dades del teu moneder són verificades pel nostre servidor dedicat',
            WARNING_SPV_P2: 'Si encara vols continuar prem "Enviar".',
            SPV_VERIFYING: 'Verificant dades de transacció',
            TX_RESULT: 'Resultat de transacció',
            KEY: 'Clau',
            INFO: 'Info',
            RESULT: 'Resultat',
            SUCCESS: 'Fet',
            PROCESSING_SM: 'Processant...',
            PROCESSING_TX: 'Processant transacció...',
            ERROR: 'Error',
            MAKE_ANOTHER_TX: 'Enviar un altre',
            NAN: 'No és un número',
            TOO_MUCH: "El màx disponible és @template@. Reenvia't algunes monedes a tu mateix per solucionar aquest error ",
            ADDRESS_IS_INCORECT: "L'adreça és incorrecta",
            QR_SCAN_ERR: 'Incapaç de desxifrar la imatge QR. Si us plau reintenta-ho.',
            SCAN_QR: 'Escaneja el codi QR',
            COINS_AMOUNT_INFO_MSG: "L'import de monedes és menor a la comissió de transacció",
            ENTER_YOUR_PASSWORD: 'Introdueix la contrassenya',
        },
        ADD_COIN: {
            SELECT_WALLETS: 'Selecciona els moneders que desitges activar',
        },
        BALANCE: {
            BALANCE: 'Saldo',
            INTEREST: 'Recompenses',
        },
        DASHBOARD: {
            CON_ERROR: 'Error de connexió. Si us plau, prova un altre servidor @template@.',
            SWITCH_SERVER: 'Canviar',
            ERROR_TESTING_SERVER: 'Error: El servidor @template@ no respòn, prova de nou',
            CONNECTING_TO_NEW_SERVER: 'Connectant a un nou servidor...',
            PROXY_ERROR: 'El servei Proxy no respòn, prova de nou',
            RETRY: 'Reintentar',        
        },
        TRANSACTIONS: {
            UNKNOWN: 'desconegut',
            NO_HISTORY: 'No hi ha historial',
            OUT: 'Surt',
            IN: 'Entra',
            MINE: 'Jo',
            IMMATURE: 'Inmadur',
            UNKNOWN: 'Desconegut',
            NO_HISTORY: 'No hi ha moviments encara',
            DIRECTION: 'Direcció',
            CONFIRMATIONS: 'Confirmacions',
            INTEREST: 'Recompenses',
            TX_HASH: 'Hash tx',
            AMOUNT: 'QUantitat',
            TIME: 'Temps',
            COIN_ADDRESS: 'Adreça',         
        },
        CLAIM: {
            WARNING: 'Avís',
            WARNING_SPV_P1: 'Les dades del teu moneder només es verifiquen per un únic servidor!',
            WARNING_SPV_P2: 'Si encara desitges continuar prem "Confirmar".',
            SPV_VERIFYING: 'Verificant dades de transacció',
            CONFIRM: 'Confirmar',
            CANCEL: 'Cancel·lar',
            FAILED_TO_CLAIM_INTEREST: 'Error al reclamar recompenses! Si us plau reintenta-ho.',
            YOU_SUCCESFULLY_CLAIMED: 'Has reclamat exitosament',
            AMOUNT: 'Import',
            INTEREST: 'Recompenses',
            INTEREST_SM: 'recompenses',
            LIST_SM: 'llista',
            REQ_TO_CLAIM_P1: 'Requisits per acumular recompenses',
            REQ_TO_CLAIM_P2: "la transacció de despesa es va fer fa almenys 1 hora, el camp de bloqueig per temps s'ha configurat y l'import és major a 10 KMD",
            CLAIM: 'Reclamar',
        },
        APP_TITLE: {
            MENU: 'Menú',
            PIN: 'Anul·lar PIN',
            LOGIN: 'Registrar-se',
            DASHBOARD: 'Panell',
            OVERVIEW: 'Vista general',
            SETTINGS: 'Configuracions',
            RECOVERY: 'Recuperar contrassenya',
            'RECOVERY-KEYS': 'Recuperar claus privades',
            SEND: 'Enviar',
            ADDCOIN: 'Afegir moneda',
            COINSALE: 'Venda Pungo token',
            'CREATE-SEED': 'Crear moneder',
            'CREATE-RECOVER-SEED': 'Recuperar moneder',
            'RECOVER-SEED': 'Recuperar moneder',
            ABOUT: 'Sobre',
            CHANGE_AUTH_METHOD: 'Canvia mètode autenticació',
            MANAGE_COINS: 'Gestionar monedes',
            LIST_OF_WALLETS: 'Llista de moneders',
            RECOVERY_OPTIONS: 'Opcions de recuperació',            
        },
        COINS: {
            //supported in pungo
            PGT: 'Pungo Token',
            SMART: 'SmartCash',
            VRSC: 'Verus',
            EQLI: 'Equaliser',
            PPC: 'Peercoin',
            TPAY: 'TokenPay',
            GRS: 'Groestlcoin',
            PIVX: 'PIVX',
            XVG: 'Verge',
            OOT: 'Utrum',
            ZILLA: 'Chainzilla',
            BCH: 'BitcoinCash',
            GAME: 'GameCredits',
            XVG: 'Verge',
            SMART: 'Smartcash',
            BTC: 'Bitcoin',
            DASH: 'Dash',
            VIA: 'Viacoin',                    
            DOGE: 'Dogecoin',
            ZEC: 'Zcash',
            GRS: 'Groestlcoin',
            QTUM: 'Qtum',
            KMD: 'Komodo',
            SUQA: 'SUQA',
            PIVX: 'Pivx',
            DGB: 'DigiByte',
            EQL: 'Equaliser',
            
            // asset chains
            BET: 'BET',
            BOTS: 'BOTS',
            CEAL: 'CEAL NET',
            COQUI: 'COQUI',
            CHAIN: 'Chainmakers',
            GLXT: 'GLXToken',            
            CRYPTO: 'CRYPTO',
            HODL: 'HODL',
            DEX: 'DEX',
            JUMBLR: 'JUMBLR',
            KV: 'KV',
            MGW: 'MultiGateway',
            MVP: 'MVP Lineup',
            MNZ: 'Monaize',
            PANGEA: 'PANGEA',
            REVS: 'REVS',
            MSHARK: 'MSHARK',
            SHARK: 'SHARK',
            MESH: 'SpaceMesh',
            SUPERNET: 'SUPERNET',
            WLC: 'WIRELESS',
            AXO: 'AXO',
            ETOMIC: 'ETOMIC',
            BTCH: 'BTCH',
            BEER: 'BEER (Test coin)',
            PIZZA: 'PIZZA (Test coin)',
            VOTE2018: 'VOTE2018 (Notary Elections)',
            NINJA: 'NINJA',
            GLXT: 'GLXToken',
            BNTN: 'Blocnation',
            PRLPAY: 'Pearl Pay',
            
            // crypto
            CRW: 'Crown',
            STRAT: 'Stratis',
            TOA: 'TOA',
            USC: 'UltimateSecureCash',
            VPN: 'VpnCoin',
            WC: 'WinCoin',
            NRG: 'Energi',
            ABY: 'ArtByte',
            VOT: 'VoteCoin',
            BDL: 'Bitdeal',
            BTCP: 'BitcoinPrivate',
            MAC: 'Machinecoin',
            XWC: 'Whitecoin',
            XVC: 'Vcash',
            CRAVE: 'Crave',
            ACC: 'AdCoin',
            AC: 'AsiaCoin',
            AUR: 'Auroracoin',
            BCA: 'Bitcoin Atom',
            CLAM: 'Clams',
            CLUB: 'ClubCoin',
            DMD: 'Diamond',
            EXCL: 'ExclusiveCoin',
            FTC: 'FeatherCoin',
            FLASH: 'Flash',
            NLG: 'Gulden',
            LCC: 'Litecoin Cash',
            MNX: 'MinexCoin',
            NAV: 'NavCoin',
            NEOS: 'NeosCoin',
            OK: 'OKCash',
            OMNI: 'OmniLayer',            
            RDD: 'Reddcoin',
            UNO: 'Unobtanium',            
            VIVO: 'VIVO',
            EFL: 'E-Gulden',
            GBX: 'GoByte',
            BSD: 'Bitsend',
            LBC: 'LBRY Credits',
            ERC: 'Europecoin',
            BATA: 'Bata',
            EMC2: 'Einsteinium',
            SYS: 'Syscoin',
            IOP: 'Internet of People',
            ZEN: 'Zencash',
            XZC: 'Zcoin',
            FJC: 'Fujicoin',            
            BCBC: 'Bitcoin CBC',
            BTG: 'BitcoinGold',           
            DNR: 'Denarius',            
            FAIR: 'Faircoin',
            ARG: 'Argentum',
            LTC: 'Litecoin',
            MONA: 'Monacoin',
            NMC: 'Namecoin',
            VTC: 'Vertcoin',
            SIB: 'Sibcoin',
            BLK: 'Blackcoin',
            HUSH: 'Hush',
            SNG: 'SnowGem',
            ZCL: 'Zclassic',
            XMY: 'Myriad',
            HODLC: 'Hodl coin',
            BTX: 'Bitcore',            
            BTCZ: 'BitcoinZ',
            CHIPS: 'Chips',
            MZC: 'Mazacoin',
            ZET: 'Zetacoin',
            SLR: 'Solarcoin',
            SMLY: 'Smileycoin',            
            RBY: 'Rubycoin',
            VOX: 'RevolutionVR',
            PUT: 'PutinCoin',
            POT: 'Potcoin',
            POSW: 'Poswcoin',
            PINK: 'Pinkcoin',
            PSB: 'Pesobit',
            NSR: 'NuShares',
            NVC: 'Novacoin',
            NYC: 'NewYorkCoin',
            NRO: 'Neuro',
            LYNX: 'Lynx',
            LINX: 'Linx',
            LDCN: 'Landcoin',
            KOBO: 'Kobocoin',
            IXC: 'Ixcoin',
            INSN: 'InsaneCoin',
            THC: 'Hempcoin',
            HNC: 'Helleniccoin',
            GRC: 'Gridcoin',
            GCR: 'Global Currency Reserve',
            FRST: 'FirstCoin',
            ERC: 'Europecoin',
            EDRC: 'EDRcoin',
            ECN: 'eCoin',
            DGC: 'Digitalcoin',
            DEFC: 'Defcoin',
            CMP: 'CompCoin',
            CCN: 'Cannacoin',
            CDN: 'Canada eCoin',
            BRIT: 'BritCoin',
            XBC: 'BitcoinPlus',
            BELA: 'BelaCoin',
            USNBT: 'NuBits',
            ONX: 'Onixcoin',
            ZET: 'Zetacoin',
            JBS: 'Jumbucks',
            SLM: 'Slimcoin',
            AXE: 'Axe',            
            MZC: 'Mazacoin',
            SDC: 'ShadowCash',
        },
    },
};

export default lang;

