const lang = {
    EN: {
        API: {
            NO_UTXO_ERR: 'UTXO(s) no disponible o error de conexión',
            CANT_BROADCAST_TX_ERR: 'No se puede transmitir la transacción',
            BAD_TX_INPUTS_SPENT_ERR: 'Se han empleado entradas de transacción incorrectas',
            CON_ERROR: 'Error de conexión. Por favor reintenta.',
            NETWORK_ERROR_TITLE: 'Ups!',
            NETWORK_ERROR_MSG: 'Parece haber algún error de conexión, por favor asegúrate que tienes conexión a internet y reintenta',
        },
        SETTINGS: {
            SAVED: 'Se han guardado los parámetros',
            AUTOLOCK_TIMEOUT: 'Tiempo de espera para autobloqueo',
            MINUTES: 'minutos',
            SAVE: 'Guardar',
            RECOVER: 'Recupera la contraseña',
            RECOVER_PRIVATE_KEYS: 'Recuperar llaves privadas',
            LOGOUT: 'Desconectar',
            REQUIRE_PIN_CONFIRM: 'Se requiere PIN para confirmar la transacción',
            ACTIVATE_WALLETS_HINT: 'Selecciona los monederos que deseas activar',
            COPIED_TO_CLIPBOARD: 'Copiado al portapapeles',
            REQUIRE_PASSWORD_CONFIRM: 'Requerir contraseña para confirmar transacción',
            AUTHORIZATION_METHOD: 'Método de autorización',
            CHANGE_PASSWORD_HINT: 'Cambiar contraseña',
            CHANGE_PIN_HINT: 'Cambiar PIN',
            CHANGE_LANGUAGE_HINT: 'Lengua',
            CHANGE_CURRENCY_HINT: 'Moneda preferida',
            REQUIRE_AUTH_CONFIRM: 'Requirir autorización para confirmar transacciones',
            DISCLAIMER_MSG_ABOUT: 'Note: all FIAT quantities are approximated using external price feed sources',
        },
        RECOVERY: {
            PROVIDE_YOUR_PIN: 'Introduce tu PIN para desbloquear',
            PROVIDE_YOUR_PASSWORD: 'Introduce tu contraseña para desbloquear',
            PROVIDE_YOUR_PIN_KEYS: 'Introduce tu PIN para desbloquear',
            PROVIDE_YOUR_PASSWORD_KEYS: 'Introduce tu contraseña para desbloquear',
            SHOW: 'Show',
            RECOVER_WALLET_HINT: 'Usa esta lista de palabras secreta para recuperar Pungo Wallet en cualquer dispositivo',
        },
        PIN: {
            SAVE: 'Guardar',
            SEED_IS_ENCRYPTED: 'La semilla está cifrada con el PIN. Usa el PIN para ingresar o firmar una transacción.',
            PROVIDE_A_PASSPHRASE: 'Proporciona una contraseña o WIF',
            PROVIDE_A_SEED: 'Proporciona una contraseña e introduce el número PIN de 6 dígitos en el formulario inferior.',
        },
        OVERVIEW: {
            PRICES_ERROR: 'La fuente de precios no es accesible',
            TOTAL_VALUE: 'Valor Total',
            PER_COIN: 'por moneda',
            YOUR_COINS: 'Tus Monedas',
            MANAGE_COINS_BTN: 'gestionar monedas',
        },
        OFFLINE: {
            TX_SIG_FAIL: 'error al firmar la transacción',
            CONFIRM: 'Confirmar',
            TX_PIN_CONFIRM: 'Para confirmar la transacción proporciona el PIN y pulsa el botón más abajo.',
            OFFLINE_TX_SIG: 'Firmando Transacción Sin conexión',
            SEND_FROM: 'Enviar de',
            SEND_TO: 'Enviar a',
            AMOUNT: 'Importe',
        },
        LOGIN: {
            OR_WIF: 'o WIF',
            CREATE_A_PIN: 'Crear un pin para el Registro.',
            SIGN_IN_TO_YOUR_ACC: 'Registra tu cuenta.',
            SIGN_IN: 'Ingresar',
            DONE: 'Hecho',
            GENERATE: 'Generar',
            PASTE: 'Pegar',
            PIN_ACCESS: 'Acceso PIN',
            WRONG_PIN: 'PIN incorrecto',
            LOGIN: 'Ingresar',
            PASSPHRASE_ACCESS: 'Contraseña de acceso',
            ENTER_PASSPHRASE: 'Introduce una contraseña',
            OVERRIDE_PIN: 'Crear / Anular PIN',
            ENTER_6_DIGIT_PIN: 'Introducir un PIN (min. 6 dígitos)',
            ENTER_PIN: 'Introduce un PIN',
            PIN_TOO_SHORT: 'El PIN es demasiado corto',
            I_CONFIRM_I_SAVED_SEED: 'Confirmo que he guardado la frase secreta en lugar seguro',
            PLEASE_MAKE_SURE_TO: 'Por favor, asegúrate de anotar la frase secreta en un sitio seguro!',
            THIS_IS_YOUR_NEW_SEED: 'Esta es tu nueva frase secreta',
            CREATE_RECOVER_WALLET: 'Crear / Recuperar Monedero',
            CONFIRMATION_REQUIRED: 'Se requiere confirmación',
            CREATE_WALLET: 'Crear monedero',
            RECOVER_WALLET: 'Recuperar monedero',
            PASSPHRASE_HINT: 'Pegar frase secreta',
            NEW_PIN_HINT: 'Introduce un nuevo PIN para acceder a tu monedero',
            GENERATE_NEW_PASSPHRASE_HINT: 'Generar nueva contraseña',
            POPUP_WARNING_MSG: 'Aviso',
            POPUP_WARNING_WIPE_WALLET: 'Si procedes tu actual monedero será BORRADO. Esta seguro?',
            WIPE_WALLET_ACTION_YES: 'Sí',
            WIPE_WALLET_ACTION_NO: 'No',
            LOGIN_WITH_PIN_HINT: 'Ingresar con pin',
            SECURITY_ENCRYPTION_METHOD_PIN: 'PIN',
            SECURITY_ENCRYPTION_METHOD_PASSWORD: 'Contraseña',
            SECURITY_ENCRYPTION_METHOD_HINT: 'Método de cifrado',
            ENTER_6_CHARS_PASSWORD: 'Introduce la contraseña (min. 6 car)',
            PASSWORD_TOO_SHORT: 'La contraseña es demasiado corta',
            NEW_PASSWORD_HINT: 'Introduce una nueva contraseña para acceder',
            INTRODUCE_OLD_PIN_HINT: 'Introduce PIN antiguo',
            INTRODUCE_NEW_PIN_HINT: 'Introduce PIN nuevo',
            CONFIRM_NEW_PIN_HINT: 'Confirma PIN nuevo',
            INTRODUCE_OLD_PASSWORD_HINT: 'Introduce contraseña antigua',
            INTRODUCE_NEW_PASSWORD_HINT: 'Introduce contraseña nueva',
            CONFIRM_NEW_PASSWORD_HINT: 'Confirma nueva contraseña',
            CONFIRM_HINT: 'Confirma',
            CANCEL_HINT: 'Cancelar',
            PASSWORDS_DO_NOT_MATCH: 'Las contraseñas no coinciden',
            PINS_DO_NOT_MATCH: 'Los PINs no coinciden',
            WRONG_PASSWORD: 'Contraseña incorrecta',
            ENTER_PASSWORD: 'Introduce contraseña',
            LOGIN_WITH_PASSWORD_HINT: 'Accede con contraseña',
            PIN_CODES_DONT_MATCH_HINT: 'Los códigos PIN no coinciden',
            RE_ENTER_6_DIGIT_PIN: 'Re-introduce el PIN',
            PASSWORDS_DONT_MATCH_HINT: 'Las contraseñas no coinciden',
            RE_ENTER_PASSWORD: 'Re-introduce la contraseña',
            OPEN_WALLET: 'Abrir cartera',
            WARNING_CREATE_WALLET_MSG: 'Crear un nuevo monedero creando una nueva frase secreta',
            WARNING_RECOVER_WALLET_MSG: 'Recupera tu monedero usando una frase secreta',
            WARNING_MSG: 'ATENCIÓ',
            WARNING_WIPE_DATA_MSG: 'Si continuas se borraran todos los datos existentes',
        },
        SEND: {
            TOTAL: 'Total',
            FEE: 'Comisión',
            BTC_FEE_SLOW: 'Lenta (60 min)',
            BTC_FEE_AVG: 'Media (30 min)',
            BTC_FEE_FAST: 'Rápida (< 30 min)',
            BTC_FEES_FETCHING: 'Extrayendo datos de comisión btc...',
            BTC_FEES_FETCHING_FAILED: 'Fallo al recuperar datos de comisión btc. Reintentando en 5s...',
            SUCCESS: 'Hecho',
            TXID: 'ID Transacción',
            OPEN_IN_EXPLORER: 'Abrir en explorador',
            ENTER_YOUR_PIN: 'Introduce tu PIN',
            SEND: 'Enviar',
            NEXT: 'Siguiente',
            BACK: 'Atrás',
            SEND_FROM: 'Enviar de',
            SEND_TO: 'Enviar a',
            SEND_ALL: 'Enviar todo',
            ENTER_AN_ADDRESS: 'Introduce una dirección',
            AMOUNT: 'Importe',
            FILL_IN_DETAILS: 'Rellena los detalles',
            CONFIRM: 'Confirmar',
            TO: 'A',
            WALLET_BALANCE: 'Saldo monedero',
            FROM: 'De',
            BALANCE: 'Saldo',
            WARNING: 'Aviso',
            WARNING_SPV_P1: 'Tus transacciones son publicadas a la red por nuestro servidor dedicado',
            WARNING_SPV_P2: 'Si todavía quiere continuar pulsa "Enviar".',
            SPV_VERIFYING: 'Verificando datos de transacción',
            TX_RESULT: 'Resultado de transacción',
            KEY: 'Clave',
            INFO: 'Info',
            RESULT: 'Resultado',
            SUCCESS: 'Éxito',
            PROCESSING_SM: 'procesando...',
            PROCESSING_TX: 'Procesando transacción...',
            ERROR: 'Error',
            MAKE_ANOTHER_TX: 'Enviar otro',
            NAN: 'No es un número',
            TOO_MUCH: 'El importe Max. disponible es @template@ reenvia el saldo máximo a tí mismo para solucionar este problema',
            ADDRESS_IS_INCORECT: 'La dirección es incorrecta',
            QR_SCAN_ERR: 'Incapaz de descifrar la imagen QR. Por favor reintentalo.',
            SCAN_QR: 'Escanea el código QR',
            COINS_AMOUNT_INFO_MSG: 'El importe de monedas es menor que la comisión de transacción',
            ENTER_YOUR_PASSWORD: 'Introduce tu contraseña',
            WARNING_CREATE_WALLET_MSG: 'Crea un nuevo monedero generando una nueva contraseña mnemotécnica',
            WARNING_RECOVER_WALLET_MSG: 'Recupera tu monedero introduciendo tu contraseña mnemotécnica',
            WARNING_MSG: 'ATENCIÓN',
            WARNING_WIPE_DATA_MSG: 'Esto eliminará todos los datos anteriores',
        },
        ADD_COIN: {
            SELECT_WALLETS: 'Selecciona las monedas que deseas activar',           
        },
        BALANCE: {
            BALANCE: 'Saldo',
            INTEREST: 'Recompensas',
        },
        DASHBOARD: {
            MY: 'Mi',
            ADDRESS: 'dirección',
            TRANSACTIONS: 'Transacciones',
            BACK: 'Atrás',
            LOGOUT: 'Desconectar',
            LOGIN: 'Ingresar',
            LOCK: 'Bloquear',
            DASHBOARD: 'Panel',
            SEND: 'Enviar',
            RECEIVE: 'Recibir',
            ADD_COIN: 'Añadir moneda',
            CREATE_SEED: 'Crear semilla',
            CON_ERROR: 'Error de conexión @template@. Por favor reintenta o reinicia la aplicación.',
            SWITCH_SERVER: 'Cambiar',
            ERROR_TESTING_SERVER: 'Error: el servidor @template@ es inalcanzable!',
            CONNECTING_TO_NEW_SERVER: 'Conectando a un nuevo servidor...',
            PROXY_ERROR: 'El servicio Proxy ha fallado, reintenta en unos minutos',
            CLAIM: 'Reclamar',
            RETRY: 'Reintentar',
            SYNC: 'Sincronizar',
            HIDE_EMPTY_WALLETS: 'Ocultar monederos vacíos',
            SHOW_EMPTY_WALLETS: 'Mostrar monederos vacíos',
        },
        TRANSACTIONS: {
            LAST_TX: 'Transacciones',
            LOADING_HISTORY: 'Cargando historial de transacciones',
            OUT: 'Sale',
            IN: 'Entra',
            MINE: 'Mío',
            IMMATURE: 'Inmaduro',
            UNKNOWN: 'Desconocido',
            NO_HISTORY: 'No hay historial',
            DIRECTION: 'Dirección',
            CONFIRMATIONS: 'Confirmaciones',
            INTEREST: 'Recompensas',
            TX_HASH: 'Hash Tx',
            AMOUNT: 'Importe',
            TIME: 'Tiempo',
            COIN_ADDRESS: 'dirección',
        },
        CLAIM: {
            WARNING: 'Aviso',
            WARNING_SPV_P1: 'los datos de tu monedero se verifican por un único servidor',
            WARNING_SPV_P2: 'Si aún deseas continuar pulsa "Confirmar".',
            SPV_VERIFYING: 'Verificando datos de transacción',
            CONFIRM: 'Confirmar',
            CANCEL: 'Cancelar',
            FAILED_TO_CLAIM_INTEREST: 'Fallo al reclamar recompensas! Por favor reintentalo.',
            YOU_SUCCESFULLY_CLAIMED: 'Has reclamado exitosamente',
            AMOUNT: 'Importe',
            INTEREST: 'Recompensas',
            INTEREST_SM: 'recompensas',
            LIST_SM: 'lista',
            REQ_TO_CLAIM_P1: 'Requisitos para acumular recompensas',
            REQ_TO_CLAIM_P2: 'la transacción de gasto se hizo hace al menos 1 hora, el campo de bloque por tiempo se ha configurado y el importe es mayor a 10 KMD',
            CLAIM: 'Reclamar',
        },
        APP_TITLE: {
            MENU: 'Menú',
            PIN: 'Anular PIN',
            LOGIN: 'Acceder',
            DASHBOARD: 'Panel',
            OVERVIEW: 'Vista general',
            SETTINGS: 'Configuración',
            RECOVERY: 'Recuperar contraseña',
            'RECOVERY-KEYS': 'Recuperar claves privadas',
            SEND: 'Enviar',
            OFFLINESIG: 'Registro sin conexión',
            ADDCOIN: 'Añadir moneda',
            COINSALE: 'Venta Pungo token',
            'CREATE-SEED': 'Crear monedero',
            'CREATE-RECOVER-SEED': 'Recuperar monedero',
            'RECOVER-SEED': 'Recuperar monedero',
            ABOUT: 'Acerca',
            CLAIM: 'Reclamar recompensas',
            MANAGE_COINS: 'Gestionar monedas',
            LIST_OF_WALLETS: 'Lista de monederos',
            PAGE_EXCHANGE: 'Intercambio',
            CHANGE_AUTH_METHOD: 'Cambia método autenticación',
            RECOVERY_OPTIONS: 'Opciones de recuperación',
        },
        COINS: {
            //supported in pungo
            PGT: 'Pungo Token',
            SMART: 'SmartCash',
            VRSC: 'Verus',
            EQLI: 'Equaliser',
            PPC: 'Peercoin',
            TPAY: 'TokenPay',
            GRS: 'Groestlcoin',
            PIVX: 'PIVX',
            XVG: 'Verge',
            OOT: 'Utrum',
            ZILLA: 'Chainzilla',
            BCH: 'BitcoinCash',
            GAME: 'GameCredits',
            XVG: 'Verge',
            SMART: 'Smartcash',
            BTC: 'Bitcoin',
            DASH: 'Dash',
            VIA: 'Viacoin',                    
            DOGE: 'Dogecoin',
            ZEC: 'Zcash',
            GRS: 'Groestlcoin',
            QTUM: 'Qtum',
            KMD: 'Komodo',
            SUQA: 'SUQA',
            PIVX: 'Pivx',
            DGB: 'DigiByte',
            EQL: 'Equaliser',
            
            // asset chains
            BET: 'BET',
            BOTS: 'BOTS',
            CEAL: 'CEAL NET',
            COQUI: 'COQUI',
            CHAIN: 'Chainmakers',
            GLXT: 'GLXToken',            
            CRYPTO: 'CRYPTO',
            HODL: 'HODL',
            DEX: 'DEX',
            JUMBLR: 'JUMBLR',
            KV: 'KV',
            MGW: 'MultiGateway',
            MVP: 'MVP Lineup',
            MNZ: 'Monaize',
            PANGEA: 'PANGEA',
            REVS: 'REVS',
            MSHARK: 'MSHARK',
            SHARK: 'SHARK',
            MESH: 'SpaceMesh',
            SUPERNET: 'SUPERNET',
            WLC: 'WIRELESS',
            AXO: 'AXO',
            ETOMIC: 'ETOMIC',
            BTCH: 'BTCH',
            BEER: 'BEER (Test coin)',
            PIZZA: 'PIZZA (Test coin)',
            VOTE2018: 'VOTE2018 (Notary Elections)',
            NINJA: 'NINJA',
            GLXT: 'GLXToken',
            BNTN: 'Blocnation',
            PRLPAY: 'Pearl Pay',
            
            // crypto
            CRW: 'Crown',
            STRAT: 'Stratis',
            TOA: 'TOA',
            USC: 'UltimateSecureCash',
            VPN: 'VpnCoin',
            WC: 'WinCoin',
            NRG: 'Energi',
            ABY: 'ArtByte',
            VOT: 'VoteCoin',
            BDL: 'Bitdeal',
            BTCP: 'BitcoinPrivate',
            MAC: 'Machinecoin',
            XWC: 'Whitecoin',
            XVC: 'Vcash',
            CRAVE: 'Crave',
            ACC: 'AdCoin',
            AC: 'AsiaCoin',
            AUR: 'Auroracoin',
            BCA: 'Bitcoin Atom',
            CLAM: 'Clams',
            CLUB: 'ClubCoin',
            DMD: 'Diamond',
            EXCL: 'ExclusiveCoin',
            FTC: 'FeatherCoin',
            FLASH: 'Flash',
            NLG: 'Gulden',
            LCC: 'Litecoin Cash',
            MNX: 'MinexCoin',
            NAV: 'NavCoin',
            NEOS: 'NeosCoin',
            OK: 'OKCash',
            OMNI: 'OmniLayer',            
            RDD: 'Reddcoin',
            UNO: 'Unobtanium',            
            VIVO: 'VIVO',
            EFL: 'E-Gulden',
            GBX: 'GoByte',
            BSD: 'Bitsend',
            LBC: 'LBRY Credits',
            ERC: 'Europecoin',
            BATA: 'Bata',
            EMC2: 'Einsteinium',
            SYS: 'Syscoin',
            IOP: 'Internet of People',
            ZEN: 'Zencash',
            XZC: 'Zcoin',
            FJC: 'Fujicoin',            
            BCBC: 'Bitcoin CBC',
            BTG: 'BitcoinGold',           
            DNR: 'Denarius',            
            FAIR: 'Faircoin',
            ARG: 'Argentum',
            LTC: 'Litecoin',
            MONA: 'Monacoin',
            NMC: 'Namecoin',
            VTC: 'Vertcoin',
            SIB: 'Sibcoin',
            BLK: 'Blackcoin',
            HUSH: 'Hush',
            SNG: 'SnowGem',
            ZCL: 'Zclassic',
            XMY: 'Myriad',
            HODLC: 'Hodl coin',
            BTX: 'Bitcore',            
            BTCZ: 'BitcoinZ',
            CHIPS: 'Chips',
            MZC: 'Mazacoin',
            ZET: 'Zetacoin',
            SLR: 'Solarcoin',
            SMLY: 'Smileycoin',            
            RBY: 'Rubycoin',
            VOX: 'RevolutionVR',
            PUT: 'PutinCoin',
            POT: 'Potcoin',
            POSW: 'Poswcoin',
            PINK: 'Pinkcoin',
            PSB: 'Pesobit',
            NSR: 'NuShares',
            NVC: 'Novacoin',
            NYC: 'NewYorkCoin',
            NRO: 'Neuro',
            LYNX: 'Lynx',
            LINX: 'Linx',
            LDCN: 'Landcoin',
            KOBO: 'Kobocoin',
            IXC: 'Ixcoin',
            INSN: 'InsaneCoin',
            THC: 'Hempcoin',
            HNC: 'Helleniccoin',
            GRC: 'Gridcoin',
            GCR: 'Global Currency Reserve',
            FRST: 'FirstCoin',
            ERC: 'Europecoin',
            EDRC: 'EDRcoin',
            ECN: 'eCoin',
            DGC: 'Digitalcoin',
            DEFC: 'Defcoin',
            CMP: 'CompCoin',
            CCN: 'Cannacoin',
            CDN: 'Canada eCoin',
            BRIT: 'BritCoin',
            XBC: 'BitcoinPlus',
            BELA: 'BelaCoin',
            USNBT: 'NuBits',
            ONX: 'Onixcoin',
            ZET: 'Zetacoin',
            JBS: 'Jumbucks',
            SLM: 'Slimcoin',
            AXE: 'Axe',            
            MZC: 'Mazacoin',
            SDC: 'ShadowCash',

        },
    },
};

export default lang;

