const lang = {
    EN: {
        API: {
            NO_UTXO_ERR: 'UTXO(s) Errore di connessione o non disponibile',
            CANT_BROADCAST_TX_ERR: 'La transazione non può essere trasmessa',
            BAD_TX_INPUTS_SPENT_ERR: 'Sono state utilizzate voci di transazione errate',
            CON_ERROR: 'Errore di connessione Si prega di riprovare.',
            NETWORK_ERROR_TITLE: 'Ops!',
            NETWORK_ERROR_MSG: 'Sembra che ci siano alcuni problemi di rete, assicurati di avere la connessione a Internet e riprova',
        },
        SETTINGS: {
            SAVED: 'I parametri sono stati salvati',
            AUTOLOCK_TIMEOUT: 'Tempo di attesa per autobloccante',
            MINUTES: 'verbale',
            SAVE: 'Salvare',
            RECOVER: 'recuperare la password',
            RECOVER_PRIVATE_KEYS: 'RECUPERARE I CHIAVI PRIVATI',
            LOGOUT: 'Disconnect',
            REQUIRE_PIN_CONFIRM: 'PIN è richiesto per confermare la transazione',
            ACTIVATE_WALLETS_HINT: 'Seleziona i portafoglio che desideri attivare',
            COPIED_TO_CLIPBOARD: 'Copiato negli appunti',
            REQUIRE_PASSWORD_CONFIRM: 'Richiedi una password per confermare la transazione',
            AUTHORIZATION_METHOD: 'Metodo di autorizzazione',
            CHANGE_PASSWORD_HINT: 'Cambia password',
            CHANGE_PIN_HINT: 'Cambia PIN',
            CHANGE_LANGUAGE_HINT: 'Lingua',
            CHANGE_CURRENCY_HINT: 'Valuta preferita',
            REQUIRE_AUTH_CONFIRM: 'Richiedere autorizzazione per confermare la transazione',
            PIN_CODES_DONT_MATCH_HINT: 'I codici PIN non corrispondono',
            RE_ENTER_6_DIGIT_PIN: 'Reinserisci codici PIN',
            PASSWORDS_DONT_MATCH_HINT: 'Le password non corrispondono',
            RE_ENTER_PASSWORD: 'Reimmettere la password',
            OPEN_WALLET: 'Aprire il portafoglio',
            DISCLAIMER_MSG_ABOUT: 'Note: all FIAT quantities are approximated using external price feed sources',
        },
        RECOVERY: {
            PROVIDE_YOUR_PIN: 'Inserisci il tuo PIN per sbloccarlo',
            PROVIDE_YOUR_PASSWORD: 'Inserisci la tua password per sbloccarla',
            PROVIDE_YOUR_PIN_KEYS: 'Inserisci il tuo PIN per sbloccarlo',
            PROVIDE_YOUR_PASSWORD_KEYS: 'Inserisci la tua password per sbloccarla',
            SHOW: "Mostra",
            RECOVER_WALLET_HINT: "Usa questa lista di parole segrete per recuperare il Portafoglio Pungo su qualsiasi dispositivo",
        },
        PIN: {
            SAVE: 'Salvare',
            SEED_IS_ENCRYPTED: 'La lista segreta di 24 parole viene crittografato con il PIN. Usa il PIN per inserire o firmare una transazione.',
            PROVIDE_A_PASSPHRASE: 'Fornire una password',
            PROVIDE_A_SEED: 'Fornire una password e inserire il numero PIN a 6 cifre nel modulo sottostante.',
        },
        OVERVIEW: {
            PRICES_ERROR: '¡Le informazioni sui prezzi non sono disponibili!',
            TOTAL_VALUE: 'Valore Totale',
            PER_COIN: 'per valuta',
            YOUR_COINS: 'Le Tue Valute',
            MANAGE_COINS_BTN: 'gestire le valute',
        },
        OFFLINE: {
            TX_SIG_FAIL: 'non è riuscito a firmare la transazione',
            CONFIRM: 'Confermare',
            TX_PIN_CONFIRM: 'Per confermare la transazione, fornire il PIN e premere il pulsante in basso.',
            OFFLINE_TX_SIG: 'Firma la Transazione Offline',
            SEND_FROM: 'Invia da',
            SEND_TO: 'Invia a',
            AMOUNT: 'Importo',
        },
        LOGIN: {
            OR_WIF: 'o WIF',
            CREATE_A_PIN: 'Creare un pin per il Registro.',
            SIGN_IN_TO_YOUR_ACC: 'Registra il tuo account Pungo',
            SIGN_IN: 'Registrazione',
            DONE: 'Fatto',
            GENERATE: 'Generare',
            PASTE: 'Pasta',
            PIN_ACCESS: 'Accesso PIN',
            WRONG_PIN: 'PIN errato!',
            LOGIN: 'Deposito',
            PASSPHRASE_ACCESS: 'Accedi alla password',
            ENTER_PASSPHRASE: 'Inserisci una password',
            OVERRIDE_PIN: 'Crea / Annulla PIN',
            ENTER_6_DIGIT_PIN: 'Inserire un codice PIN (minimo 6 cifre)',
            ENTER_PIN: 'Inserisci un PIN',
            PIN_TOO_SHORT: 'Il PIN è troppo corto!',
            I_CONFIRM_I_SAVED_SEED: 'Confermo di aver salvato la lista segreta di 24 parole',
            PLEASE_MAKE_SURE_TO: 'Si prega di essere sicuri di salvaguardarlo in un luogo sicuro!',
            THIS_IS_YOUR_NEW_SEED: 'Questo è la tua la lista segreta di 24 parole',
            CREATE_RECOVER_WALLET: 'Crea / Recupera Portafoglio',
            CONFIRMATION_REQUIRED: 'Richiesta conferma',
            CREATE_WALLET: 'Creare portafoglio',
            RECOVER_WALLET: 'Recuperare il portafoglio',
            PASSPHRASE_HINT: 'Incolla una lista segreta di 24 parole ',
            NEW_PIN_HINT: 'Inserisci un nuovo PIN per accedere al tuo portafoglio',
            GENERATE_NEW_PASSPHRASE_HINT: 'Genera nuova password',
            POPUP_WARNING_MSG: 'Avvertimento',
            POPUP_WARNING_WIPE_WALLET: 'Se procedete, il vostro portafoglio corrente verrà CANCELLATO. Sei sicuro?',
            WIPE_WALLET_ACTION_YES: 'Sì',
            WIPE_WALLET_ACTION_NO: 'No',
            LOGIN_WITH_PIN_HINT: 'inserisci con il pin',
            SECURITY_ENCRYPTION_METHOD_PIN: "PIN",
            SECURITY_ENCRYPTION_METHOD_PASSWORD: "Password",
            SECURITY_ENCRYPTION_METHOD_HINT: "Metodo di crittografia di sicurezza",
            ENTER_6_CHARS_PASSWORD: "Password (almeno 6 caratteri)",
            PASSWORD_TOO_SHORT: "Password troppo breve",
            NEW_PASSWORD_HINT: 'Imposta una nuova password per accedere al tuo portafoglio',
            INTRODUCE_OLD_PIN_HINT: "Introduci il vecchio PIN",
            INTRODUCE_NEW_PIN_HINT: "Introduci nuovo PIN",
            CONFIRM_NEW_PIN_HINT: "Conferma nuovo PIN",
            INTRODUCE_OLD_PASSWORD_HINT: "Inserisci la vecchia password",
            INTRODUCE_NEW_PASSWORD_HINT: "Inserisci la nuova password",
            CONFIRM_NEW_PASSWORD_HINT: 'Conferma la password di noveueu',
            CONFIRM_HINT: 'Conferma',
            CANCEL_HINT: 'Annulla',
            PASSWORDS_DO_NOT_MATCH: "Le password non corrispondono",
            PINS_DO_NOT_MATCH: "I PIN non corrispondono",
            WRONG_PASSWORD: "Password errata",
            ENTER_PASSWORD: 'Inserisci password',
            LOGIN_WITH_PASSWORD_HINT: "Accedi con password",   
            OPEN_WALLET: "Portafoglio aperto",
            WARNING_CREATE_WALLET_MSG: 'Crea un nuovo portafoglio generando una nuova lista segreta di 24 parole',
            WARNING_RECOVER_WALLET_MSG: 'Recupera il tuo portafoglio inserendo la lista segreta di 24 parole',
            WARNING_MSG: 'AVVERTIMENTO',
            WARNING_WIPE_DATA_MSG: 'Questo cancellerà tutti i dati precedenti',         
        },
        SEND: {
            TOTAL: 'Totale',
            FEE: 'Commissione',
            BTC_FEE_SLOW: 'Lento (60 min)',
            BTC_FEE_AVG: 'Media (30 minuti)',
            BTC_FEE_FAST: 'Veloce (<30 minuti)',
            BTC_FEES_FETCHING: 'Estrazione dei dati della commissione btc ...',
            BTC_FEES_FETCHING_FAILED: 'Impossibile recuperare i dati della commissione btc. Nuovo tentativo in 5s ...',
            SUCCESS: 'Successo',
            TXID: 'ID Transazione',
            OPEN_IN_EXPLORER: 'Apri nel browser',
            ENTER_YOUR_PIN: 'Inserisci il tuo PIN',
            SEND: 'Inviare',
            NEXT: 'Seguente',
            BACK: 'Indietro',
            SEND_FROM: 'Invia da',
            SEND_TO: 'Invia a',
            SEND_ALL: 'Invia tutto',
            ENTER_AN_ADDRESS: 'Inserisci un indirizzo',
            AMOUNT: 'Importo',
            FILL_IN_DETAILS: 'Compila i dettagli',
            CONFIRM: 'Confermare',
            TO: 'Inviare a',
            WALLET_BALANCE: 'Saldo del portafoglio',
            FROM: 'Invia da',
            BALANCE: 'Saldo',
            WARNING: 'Avvertimento',
            WARNING_SPV_P1: 'I dati del tuo portafoglio sono verificati solo da un singolo server!',
            WARNING_SPV_P2: 'Se vuoi continuare, premi "Invia".',
            SPV_VERIFYING: 'Verifica dei dati della transazione',
            TX_RESULT: 'Risultato della transazione',
            KEY: 'Chiave',
            INFO: 'Info',
            RESULT: 'Risultato',
            SUCCESS: 'successo',
            PROCESSING_SM: 'elaborazione...',
            PROCESSING_TX: 'Elaborazione della transazione...',
            ERROR: 'Errore',
            MAKE_ANOTHER_TX: 'Invia un altro',
            NAN: 'Non è un numero',
            TOO_MUCH: "Il numero è troppo grande. L'importo Max. disponibile è @template@",
            ADDRESS_IS_INCORECT: "L'indirizzo non è corretto",
            QR_SCAN_ERR: "Impossibile decifrare l'immagine QR. Si prega di riprovare.",
            SCAN_QR: 'Scansiona il codice QR',
            COINS_AMOUNT_INFO_MSG: 'La quantità di monete è inferiore alla commissione di transazione',
            ENTER_YOUR_PASSWORD: "Inserisci password",
        },
        ADD_COIN: {
            ADD_ALL_COINS: 'Aggiungi tutte le monete',
            SHORTCUTS: 'Scorciatoie',
            MULTI_SELECT: 'Multi-selezione',
            ADD_SELECTED_COINS: 'Aggiungi monete selezionate',
            NEXT: 'Seguente',
            SELECT_WALLETS: 'Seleziona i portafoglio che desideri attivare',
        },
        BALANCE: {
            BALANCE: 'Saldo',
            INTEREST: 'Ricompense',
        },
        DASHBOARD: {
            MY: 'Il mio',
            ADDRESS: 'indirizzo',
            TRANSACTIONS: 'Relazioni',
            BACK: 'Indietro',
            LOGOUT: 'Disconnect',
            LOGIN: 'Deposito',
            LOCK: 'Bloccare',
            DASHBOARD: 'Pannello',
            SEND: 'Inviare',
            RECEIVE: 'Ricevere',
            ADD_COIN: 'Aggiungi valuta',
            CREATE_SEED: 'Crea seme',
            CON_ERROR: 'Errore di connessione Per favore, prova un altro server @template@.',
            SWITCH_SERVER: 'Cambiamento',
            ERROR_TESTING_SERVER: 'Errore: il server @template@ non è raggiungibile!',
            CONNECTING_TO_NEW_SERVER: 'Connessione a un nuovo server ...',
            PROXY_ERROR: 'Il servizio proxy è irraggiungibile!',
            CLAIM: 'Affermazione',
            RETRY: 'Riprovare',
            SYNC: 'Sincronizzare',
            HIDE_EMPTY_WALLETS: 'Nascondi le borse vuote',
            SHOW_EMPTY_WALLETS: 'Mostra borse vuote',
        },
        TRANSACTIONS: {
            LAST_TX: 'Relazioni',
            LOADING_HISTORY: 'Caricamento della cronologia delle transazioni',
            OUT: 'Inviato',
            IN: 'Ricevuto',
            MINE: 'Io',
            IMMATURE: 'immaturo',
            UNKNOWN: 'sconosciuto',
            NO_HISTORY: 'Nessuna storia',
            DIRECTION: 'Indirizzo',
            CONFIRMATIONS: 'Conferme',
            INTEREST: 'Ricompense',
            TX_HASH: 'Hash Tx',
            AMOUNT: 'Importo',
            TIME: 'Tempo',
            COIN_ADDRESS: 'Indirizzo',
        },
        CLAIM: {
            WARNING: 'Avvertimento',
            WARNING_SPV_P1: 'I dati del tuo portafoglio sono verificati solo da un singolo server!',
            WARNING_SPV_P2: 'Se vuoi continuare, premi "Conferma".',
            SPV_VERIFYING: 'Verifica dei dati della transazione',
            CONFIRM: 'Confermare',
            CANCEL: 'Annullare',
            FAILED_TO_CLAIM_INTEREST: 'Non riescono a richiedere premi! Si prega di riprovare.',
            YOU_SUCCESFULLY_CLAIMED: 'Hai reclamato con successo',
            AMOUNT: 'Importo',
            INTEREST: 'Ricompense',
            INTEREST_SM: 'Ricompense',
            LIST_SM: 'lista',
            REQ_TO_CLAIM_P1: 'Requisiti per accumulare premi',
            REQ_TO_CLAIM_P2: "la transazione di spesa è stata effettuata almeno 1 ora fa, il campo di blocco per ora è stato configurato e l'importo è maggiore di 10 KMD",
            CLAIM: 'Affermazione',
        },
        APP_TITLE: {
            MENU: 'Menu',
            PIN: 'Annulla PIN',
            LOGIN: 'Registrazione',
            DASHBOARD: 'Pannello',
            OVERVIEW: 'Vista generale',
            SETTINGS: 'Configurazioni',
            RECOVERY: 'Recupera password',
            'RECOVERY-KEYS': 'Recupera chiavi private',
            SEND: 'Inviare',
            OFFLINESIG: 'Registrazione offline',
            ADDCOIN: 'Aggiungi valuta',
            COINSALE: 'Vendita Pungo token',
            'CREATE-SEED': 'Crea borsa',
            'CREATE-RECOVER-SEED': 'Recupera la borsa',
            'RECOVER-SEED': 'Recupera la borsa',
            ABOUT: 'Su',
            CLAIM: 'Richiedi premi',
            MANAGE_COINS: 'Gestisci le valute',
            LIST_OF_WALLETS: 'Elenco delle borse',
            PAGE_EXCHANGE: 'Scambio',
            CHANGE_AUTH_METHOD: 'Cambia metodo di autenticazione',
            RECOVERY_OPTIONS: 'Opzioni di recupero',
        },
        COINS: {
            //supported in pungo
            PGT: 'Pungo Token',
            SMART: 'SmartCash',
            VRSC: 'Verus',
            EQLI: 'Equaliser',
            PPC: 'Peercoin',
            TPAY: 'TokenPay',
            GRS: 'Groestlcoin',
            PIVX: 'PIVX',
            XVG: 'Verge',
            OOT: 'Utrum',
            ZILLA: 'Chainzilla',
            BCH: 'BitcoinCash',
            GAME: 'GameCredits',
            XVG: 'Verge',
            SMART: 'Smartcash',
            BTC: 'Bitcoin',
            DASH: 'Dash',
            VIA: 'Viacoin',                    
            DOGE: 'Dogecoin',
            ZEC: 'Zcash',
            GRS: 'Groestlcoin',
            QTUM: 'Qtum',
            KMD: 'Komodo',
            SUQA: 'SUQA',
            PIVX: 'Pivx',
            DGB: 'DigiByte',
            EQL: 'Equaliser',
            
            // asset chains
            BET: 'BET',
            BOTS: 'BOTS',
            CEAL: 'CEAL NET',
            COQUI: 'COQUI',
            CHAIN: 'Chainmakers',
            GLXT: 'GLXToken',            
            CRYPTO: 'CRYPTO',
            HODL: 'HODL',
            DEX: 'DEX',
            JUMBLR: 'JUMBLR',
            KV: 'KV',
            MGW: 'MultiGateway',
            MVP: 'MVP Lineup',
            MNZ: 'Monaize',
            PANGEA: 'PANGEA',
            REVS: 'REVS',
            MSHARK: 'MSHARK',
            SHARK: 'SHARK',
            MESH: 'SpaceMesh',
            SUPERNET: 'SUPERNET',
            WLC: 'WIRELESS',
            AXO: 'AXO',
            ETOMIC: 'ETOMIC',
            BTCH: 'BTCH',
            BEER: 'BEER (Test coin)',
            PIZZA: 'PIZZA (Test coin)',
            VOTE2018: 'VOTE2018 (Notary Elections)',
            NINJA: 'NINJA',
            GLXT: 'GLXToken',
            BNTN: 'Blocnation',
            PRLPAY: 'Pearl Pay',
            
            // crypto
            CRW: 'Crown',
            STRAT: 'Stratis',
            TOA: 'TOA',
            USC: 'UltimateSecureCash',
            VPN: 'VpnCoin',
            WC: 'WinCoin',
            NRG: 'Energi',
            ABY: 'ArtByte',
            VOT: 'VoteCoin',
            BDL: 'Bitdeal',
            BTCP: 'BitcoinPrivate',
            MAC: 'Machinecoin',
            XWC: 'Whitecoin',
            XVC: 'Vcash',
            CRAVE: 'Crave',
            ACC: 'AdCoin',
            AC: 'AsiaCoin',
            AUR: 'Auroracoin',
            BCA: 'Bitcoin Atom',
            CLAM: 'Clams',
            CLUB: 'ClubCoin',
            DMD: 'Diamond',
            EXCL: 'ExclusiveCoin',
            FTC: 'FeatherCoin',
            FLASH: 'Flash',
            NLG: 'Gulden',
            LCC: 'Litecoin Cash',
            MNX: 'MinexCoin',
            NAV: 'NavCoin',
            NEOS: 'NeosCoin',
            OK: 'OKCash',
            OMNI: 'OmniLayer',            
            RDD: 'Reddcoin',
            UNO: 'Unobtanium',            
            VIVO: 'VIVO',
            EFL: 'E-Gulden',
            GBX: 'GoByte',
            BSD: 'Bitsend',
            LBC: 'LBRY Credits',
            ERC: 'Europecoin',
            BATA: 'Bata',
            EMC2: 'Einsteinium',
            SYS: 'Syscoin',
            IOP: 'Internet of People',
            ZEN: 'Zencash',
            XZC: 'Zcoin',
            FJC: 'Fujicoin',            
            BCBC: 'Bitcoin CBC',
            BTG: 'BitcoinGold',           
            DNR: 'Denarius',            
            FAIR: 'Faircoin',
            ARG: 'Argentum',
            LTC: 'Litecoin',
            MONA: 'Monacoin',
            NMC: 'Namecoin',
            VTC: 'Vertcoin',
            SIB: 'Sibcoin',
            BLK: 'Blackcoin',
            HUSH: 'Hush',
            SNG: 'SnowGem',
            ZCL: 'Zclassic',
            XMY: 'Myriad',
            HODLC: 'Hodl coin',
            BTX: 'Bitcore',            
            BTCZ: 'BitcoinZ',
            CHIPS: 'Chips',
            MZC: 'Mazacoin',
            ZET: 'Zetacoin',
            SLR: 'Solarcoin',
            SMLY: 'Smileycoin',            
            RBY: 'Rubycoin',
            VOX: 'RevolutionVR',
            PUT: 'PutinCoin',
            POT: 'Potcoin',
            POSW: 'Poswcoin',
            PINK: 'Pinkcoin',
            PSB: 'Pesobit',
            NSR: 'NuShares',
            NVC: 'Novacoin',
            NYC: 'NewYorkCoin',
            NRO: 'Neuro',
            LYNX: 'Lynx',
            LINX: 'Linx',
            LDCN: 'Landcoin',
            KOBO: 'Kobocoin',
            IXC: 'Ixcoin',
            INSN: 'InsaneCoin',
            THC: 'Hempcoin',
            HNC: 'Helleniccoin',
            GRC: 'Gridcoin',
            GCR: 'Global Currency Reserve',
            FRST: 'FirstCoin',
            ERC: 'Europecoin',
            EDRC: 'EDRcoin',
            ECN: 'eCoin',
            DGC: 'Digitalcoin',
            DEFC: 'Defcoin',
            CMP: 'CompCoin',
            CCN: 'Cannacoin',
            CDN: 'Canada eCoin',
            BRIT: 'BritCoin',
            XBC: 'BitcoinPlus',
            BELA: 'BelaCoin',
            USNBT: 'NuBits',
            ONX: 'Onixcoin',
            ZET: 'Zetacoin',
            JBS: 'Jumbucks',
            SLM: 'Slimcoin',
            AXE: 'Axe',            
            MZC: 'Mazacoin',
            SDC: 'ShadowCash',

        },
    },
};

export default lang;

