const lang = {
    EN: {
        API: {
            NO_UTXO_ERR: 'UTXO(s) não disponível ou erro de conexão',
            CANT_BROADCAST_TX_ERR: 'A transação não pode ser transmitida',
            BAD_TX_INPUTS_SPENT_ERR: 'Entradas de transação incorretas foram usadas',
            CON_ERROR: 'Erro de conexão. Por favor, tente novamente.',
            NETWORK_ERROR_TITLE: 'Ops!',
            NETWORK_ERROR_MSG: 'Parece que há alguns problemas de rede, verifique se você tem conexão com a Internet e tente novamente',
        },
        SETTINGS: {
            SAVED: 'Os parâmetros foram salvos',
            AUTOLOCK_TIMEOUT: 'Tempo de espera para o autotravamento',
            MINUTES: 'minutos',
            SAVE: 'Salvar',
            RECOVER: 'recuperar a senha',
            RECOVER_PRIVATE_KEYS: 'RECUPERAR CHAVES PRIVADAS',
            LOGOUT: 'desconectar',
            REQUIRE_PIN_CONFIRM: 'PIN é necessário para confirmar a transação',
            ACTIVATE_WALLETS_HINT: 'Selecione as bolsas que você deseja ativar',
            COPIED_TO_CLIPBOARD: 'Copiado para a área de transferência',
            REQUIRE_PASSWORD_CONFIRM: 'Requer senha para confirmar a transação',
            AUTHORIZATION_METHOD: 'Método de autorização',
            CHANGE_PASSWORD_HINT: 'Alterar senha',
            CHANGE_PIN_HINT: "Alterar PIN",
            CHANGE_LANGUAGE_HINT: 'Idioma',
            CHANGE_CURRENCY_HINT: "moeda preferida",
            REQUIRE_AUTH_CONFIRM: 'Exigir autorização para confirmar a transação',
            DISCLAIMER_MSG_ABOUT: 'Note: all FIAT quantities are approximated using external price feed sources',
        },
        RECOVERY: {   
            PROVIDE_YOUR_PIN: 'Digite seu PIN para desbloquear',
            PROVIDE_YOUR_PASSWORD: 'Digite sua senha para desbloquear',
            PROVIDE_YOUR_PIN_KEYS: 'Introduza o seu PIN para desbloquear',
            PROVIDE_YOUR_PASSWORD_KEYS: 'Digite sua senha para desbloquear',
            SHOW: 'Mostra',
            RECOVER_WALLET_HINT: 'Use esta lista secreta de palavras para recuperar a Pungo Wallet em qualquer dispositivo',
        },
        PIN: {
            SAVE: 'Salvar',
            SEED_IS_ENCRYPTED: 'A semente é criptografada com o PIN entregue. Use o PIN para inserir ou assinar uma transação.',
            PROVIDE_A_PASSPHRASE: 'Fornecer uma senha ou WIF',
            PROVIDE_A_SEED: 'Forneça uma senha e insira o número PIN de 6 dígitos no formulário abaixo.',
        },
        OVERVIEW: {
            PRICES_ERROR: 'Atomicexplorer.com não está acessível!',
            TOTAL_VALUE: 'Valor Total',
            PER_COIN: 'por moeda',
            YOUR_COINS: 'Suas Moedas',
            MANAGE_COINS_BTN: 'gerenciar moedas',
        },
        OFFLINE: {
            TX_SIG_FAIL: 'não conseguiu assinar a transação',
            CONFIRM: 'Confirmar',
            TX_PIN_CONFIRM: 'Para confirmar a transação, forneça o PIN e pressione o botão abaixo.',
            OFFLINE_TX_SIG: 'Assinatura de transação off-line',
            SEND_FROM: 'Envie de',
            SEND_TO: 'Enviar para',
            AMOUNT: 'Quantidade',
        },
        LOGIN: {
            OR_WIF: 'ou WIF',
            CREATE_A_PIN: 'Crie um alfinete para o Registro.',
            SIGN_IN_TO_YOUR_ACC: 'Registre sua conta do Agama.',
            SIGN_IN: 'Registrese',
            DONE: 'Feito',
            GENERATE: 'Gerar',
            PASTE: 'Colar',
            PIN_ACCESS: 'Acesso PIN',
            WRONG_PIN: 'PIN incorreto!',
            LOGIN: 'Entrar',
            PASSPHRASE_ACCESS: 'Senha de acesso',
            ENTER_PASSPHRASE: 'Digite uma senha',
            OVERRIDE_PIN: 'Criar / Cancelar PIN',
            ENTER_6_DIGIT_PIN: 'Digite um PIN (6 dígitos no mínimo)',
            ENTER_PIN: 'Digite um PIN',
            PIN_TOO_SHORT: 'O PIN é muito curto!',
            I_CONFIRM_I_SAVED_SEED: 'Eu confirmo que salvei a semente',
            PLEASE_MAKE_SURE_TO: 'Por favor, certifique-se de anotá-lo e protegê-lo em um lugar seguro!',
            THIS_IS_YOUR_NEW_SEED: 'Esta é sua nova semente',
            CREATE_RECOVER_WALLET: 'Criar / Recuperar Carteira',
            CONFIRMATION_REQUIRED: 'Confirmação necessária',
            CREATE_WALLET: 'Criar Carteira',
            RECOVER_WALLET: 'Recupere a Carteira',
            PASSPHRASE_HINT: 'Cole uma senha ou WIF existente',
            NEW_PIN_HINT: 'Insira um novo PIN para acessar sua carteira',
            GENERATE_NEW_PASSPHRASE_HINT: 'Gerar nova senha',
            POPUP_WARNING_MSG: 'Aviso',
            POPUP_WARNING_WIPE_WALLET: 'Se você continuar, sua bolsa atual será LIMPADA. Tem certeza?',
            WIPE_WALLET_ACTION_YES: 'Sim',
            WIPE_WALLET_ACTION_NO: 'No',
            LOGIN_WITH_PIN_HINT: 'entre com pin',
            SECURITY_ENCRYPTION_METHOD_PIN: 'PIN',
            SECURITY_ENCRYPTION_METHOD_PASSWORD: 'Password',
            SECURITY_ENCRYPTION_METHOD_HINT: 'método de segurança',
            ENTER_6_CHARS_PASSWORD: 'Digite uma senha (min. 6 carro)',
            PASSWORD_TOO_SHORT: 'Senha muito curta!',
            NEW_PASSWORD_HINT: 'Digite uma nova senha para acessar a carteira',
            INTRODUCE_OLD_PIN_HINT: 'Digite o PIN antigo',
            INTRODUCE_NEW_PIN_HINT: 'Digite um novo PIN',
            CONFIRM_NEW_PIN_HINT: 'Confirmar novo PIN',
            INTRODUCE_OLD_PASSWORD_HINT: 'Digite a senha antiga',
            INTRODUCE_NEW_PASSWORD_HINT: 'Insira a nova senha',
            CONFIRM_NEW_PASSWORD_HINT: 'Confirme a nova senha',
            CONFIRM_HINT: 'Confirmar',
            CANCEL_HINT: 'Cancelar',
            PASSWORDS_DO_NOT_MATCH: 'Senhas não combinam',
            PINS_DO_NOT_MATCH: 'PINs não correspondem',
            WRONG_PASSWORD: 'Senha incorreta!',
            ENTER_PASSWORD: 'Digite a senha',
            LOGIN_WITH_PASSWORD_HINT: 'acesso com senha',
            PIN_CODES_DONT_MATCH_HINT: 'Os códigos PIN não correspondem',
            RE_ENTER_6_DIGIT_PIN: 'reintroduzir o código PIN',
            PASSWORDS_DONT_MATCH_HINT: 'As palavras-passe não combinam',
            RE_ENTER_PASSWORD: 'Digite novamente a senha',
            OPEN_WALLET: 'Abrir a carteira',
            WARNING_CREATE_WALLET_MSG: 'Crie uma nova carteira gerando uma nova senha mnemônica',
            WARNING_RECOVER_WALLET_MSG: 'Recupere sua carteira inserindo sua senha mnemônica',
            WARNING_MSG: 'AVISO',
            WARNING_WIPE_DATA_MSG: 'Isso limpará todos os dados anteriores',
            
        },
        SEND: {
            TOTAL: 'Total',
            FEE: 'Comissão',
            BTC_FEE_SLOW: 'Lenta (60 min)',
            BTC_FEE_AVG: 'Média (30 min)',
            BTC_FEE_FAST: 'Rápido (<30 min)',
            BTC_FEES_FETCHING: 'Extraindo dados da comissão btc ...',
            BTC_FEES_FETCHING_FAILED: 'Falha ao recuperar os dados da comissão btc. Tentando novamente em 5s ...',
            SUCCESS: 'Sucesso',
            TXID: 'ID de Transação',
            OPEN_IN_EXPLORER: 'Abra no navegador',
            ENTER_YOUR_PIN: 'Digite seu PIN',
            SEND: 'Enviar',
            NEXT: 'Próximo',
            BACK: 'Voltar',
            SEND_FROM: 'Envie de',
            SEND_TO: 'Enviar para',
            SEND_ALL: 'Enviar tudo',
            ENTER_AN_ADDRESS: 'Digite um endereço',
            AMOUNT: 'Quantidade',
            FILL_IN_DETAILS: 'Preencha os detalhes',
            CONFIRM: 'Confirmar',
            TO: 'Enviar para',
            WALLET_BALANCE: 'Saldo da carteira',
            FROM: 'Envie de',
            BALANCE: 'Saldo',
            WARNING: 'Aviso',
            WARNING_SPV_P1: 'Seus dados da carteira são verificados apenas por um único servidor!',
            WARNING_SPV_P2: 'Se você ainda quiser continuar, pressione "Enviar".',
            SPV_VERIFYING: 'Verificando dados de transação',
            TX_RESULT: 'Resultado da transação',
            KEY: 'Key',
            INFO: 'Info',
            RESULT: 'Resultado',
            SUCCESS: 'sucesso',
            PROCESSING_SM: 'processando ...',
            PROCESSING_TX: 'Processando transação ...',
            ERROR: 'Erro',
            MAKE_ANOTHER_TX: 'Envie outro',
            NAN: 'Não é um número',
            TOO_MUCH: 'O número é muito grande. A quantidade máx. disponível é @template@',
            ADDRESS_IS_INCORECT: 'O endereço está incorreto',
            QR_SCAN_ERR: 'Não é possível decifrar a imagem QR. Por favor, tente novamente.',
            SCAN_QR: 'Digitalize o código QR',
            COINS_AMOUNT_INFO_MSG: 'A quantidade de moedas é menor que a taxa de transação',
            ENTER_YOUR_PASSWORD: 'Digite a senha',
        },
        ADD_COIN: {
            ADD_ALL_COINS: 'Adicione todas as moedas',
            SHORTCUTS: 'Atalhos',
            MULTI_SELECT: 'Multi-seleção',
            ADD_SELECTED_COINS: 'Adicione moedas selecionadas',
            NEXT: 'Próximo',
            SELECT_WALLETS: 'Selecione as carteiras que você deseja ativar'
        },
        BALANCE: {
            BALANCE: 'Saldo',
            INTEREST: 'Recompensas',
        },
        DASHBOARD: {
            MY: 'Mi',
            ADDRESS: 'Direção',
            TRANSACTIONS: 'Transações',
            BACK: 'Voltar',
            LOGOUT: 'Desconectar',
            LOGIN: 'Entrar',
            LOCK: 'Bloco',
            DASHBOARD: 'Painel',
            SEND: 'Enviar',
            RECEIVE: 'Receba',
            ADD_COIN: 'Adicionar moeda',
            CREATE_SEED: 'Criar semente',
            CON_ERROR: 'Erro de conexão Por favor, tente outro servidor @template@.',
            SWITCH_SERVER: 'Alterar',
            ERROR_TESTING_SERVER: 'Erro: o servidor @template@ está inacessível!',
            CONNECTING_TO_NEW_SERVER: 'Conectando-se a um novo servidor ...',
            PROXY_ERROR: 'O serviço de proxy está inacessível!',
            CLAIM: 'Reivindicação',
            RETRY: 'Tente novamente',
            SYNC: 'Sincronizar',
            HIDE_EMPTY_WALLETS: 'Esconder as carteiras vazias',
            SHOW_EMPTY_WALLETS: 'Mostrar carteiras vazias',
        },
        TRANSACTIONS: {
            LAST_TX: 'Transações',
            LOADING_HISTORY: 'Carregando histórico de transações',
            OUT: 'Enviado',
            IN: 'Recebido',
            MINE: 'Eu',
            IMMATURE: 'imaturo',
            UNKNOWN: 'desconhecido',
            NO_HISTORY: 'Sem história',
            DIRECTION: 'Endereço',
            CONFIRMATIONS: 'Confirmações',
            INTEREST: 'Recompensas',
            TX_HASH: 'Hash Tx',
            AMOUNT: 'Quantidade',
            TIME: 'Tempo',
            COIN_ADDRESS: 'direção'
        },
        CLAIM: {
            WARNING: 'Aviso',
            WARNING_SPV_P1: 'Seus dados da carteira só são verificados por um único servidor!',
            WARNING_SPV_P2: 'Se você ainda quiser continuar, pressione "Confirmar".',
            SPV_VERIFYING: 'Verificando dados de transação',
            CONFIRM: 'Confirmar',
            CANCEL: 'Cancelar',
            FAILED_TO_CLAIM_INTEREST: 'Não reivindique recompensas! Por favor, tente novamente.',
            YOU_SUCCESFULLY_CLAIMED: 'Você recuperou com sucesso',
            AMOUNT: 'Quantidade',
            INTEREST: 'Recompensas',
            INTEREST_SM: 'recompensas',
            LIST_SM: 'listar',
            REQ_TO_CLAIM_P1: 'Requisitos para acumular recompensas',
            REQ_TO_CLAIM_P2: 'a transação de despesa foi feita há pelo menos 1 hora, o campo de bloqueio por tempo foi configurado e o valor é maior que 10 KMD',
            CLAIM: 'Reivindicação',
        },
        APP_TITLE: {
            MENU: 'Cardápio',
            PIN: 'Cancelar PIN',
            LOGIN: 'Entrar',
            DASHBOARD: 'Painel',
            OVERVIEW: 'Visão global',
            SETTINGS: 'Configurações',
            RECOVERY: 'Recuperar senha',
            'RECOVERY-KEYS': 'Recuperar senha',
            SEND: 'Enviar',
            OFFLINESIG: 'Registro off-line',
            ADDCOIN: 'Adicionar moeda',
            COINSALE: 'Venda Pungo token',
            'CREATE-SEED': 'Criar carteira',
            'CREATE-RECOVER-SEED': 'Recupere a carteira',
            'RECOVER-SEED': 'Recupere a carteira',
            ABOUT: 'Sobre',
            CLAIM: 'Reivindicar recompensas',
            MANAGE_COINS: 'Gerenciar moedas',
            LIST_OF_WALLETS: 'Lista de carteiras',
            PAGE_EXCHANGE: 'Troca',
            CHANGE_AUTH_METHOD: 'Alterar o método de autenticação',
            RECOVERY_OPTIONS: 'Opções de recuperação',
        },
       COINS: {
            //supported in pungo
            PGT: 'Pungo Token',
            SMART: 'SmartCash',
            VRSC: 'Verus',
            EQLI: 'Equaliser',
            PPC: 'Peercoin',
            TPAY: 'TokenPay',
            GRS: 'Groestlcoin',
            PIVX: 'PIVX',
            XVG: 'Verge',
            OOT: 'Utrum',
            ZILLA: 'Chainzilla',
            BCH: 'BitcoinCash',
            GAME: 'GameCredits',
            XVG: 'Verge',
            SMART: 'Smartcash',
            BTC: 'Bitcoin',
            DASH: 'Dash',
            VIA: 'Viacoin',                    
            DOGE: 'Dogecoin',
            ZEC: 'Zcash',
            GRS: 'Groestlcoin',
            QTUM: 'Qtum',
            KMD: 'Komodo',
            SUQA: 'SUQA',
            PIVX: 'Pivx',
            DGB: 'DigiByte',
            EQL: 'Equaliser',
            
            // asset chains
            BET: 'BET',
            BOTS: 'BOTS',
            CEAL: 'CEAL NET',
            COQUI: 'COQUI',
            CHAIN: 'Chainmakers',
            GLXT: 'GLXToken',            
            CRYPTO: 'CRYPTO',
            HODL: 'HODL',
            DEX: 'DEX',
            JUMBLR: 'JUMBLR',
            KV: 'KV',
            MGW: 'MultiGateway',
            MVP: 'MVP Lineup',
            MNZ: 'Monaize',
            PANGEA: 'PANGEA',
            REVS: 'REVS',
            MSHARK: 'MSHARK',
            SHARK: 'SHARK',
            MESH: 'SpaceMesh',
            SUPERNET: 'SUPERNET',
            WLC: 'WIRELESS',
            AXO: 'AXO',
            ETOMIC: 'ETOMIC',
            BTCH: 'BTCH',
            BEER: 'BEER (Test coin)',
            PIZZA: 'PIZZA (Test coin)',
            VOTE2018: 'VOTE2018 (Notary Elections)',
            NINJA: 'NINJA',
            GLXT: 'GLXToken',
            BNTN: 'Blocnation',
            PRLPAY: 'Pearl Pay',
            
            // crypto
            CRW: 'Crown',
            STRAT: 'Stratis',
            TOA: 'TOA',
            USC: 'UltimateSecureCash',
            VPN: 'VpnCoin',
            WC: 'WinCoin',
            NRG: 'Energi',
            ABY: 'ArtByte',
            VOT: 'VoteCoin',
            BDL: 'Bitdeal',
            BTCP: 'BitcoinPrivate',
            MAC: 'Machinecoin',
            XWC: 'Whitecoin',
            XVC: 'Vcash',
            CRAVE: 'Crave',
            ACC: 'AdCoin',
            AC: 'AsiaCoin',
            AUR: 'Auroracoin',
            BCA: 'Bitcoin Atom',
            CLAM: 'Clams',
            CLUB: 'ClubCoin',
            DMD: 'Diamond',
            EXCL: 'ExclusiveCoin',
            FTC: 'FeatherCoin',
            FLASH: 'Flash',
            NLG: 'Gulden',
            LCC: 'Litecoin Cash',
            MNX: 'MinexCoin',
            NAV: 'NavCoin',
            NEOS: 'NeosCoin',
            OK: 'OKCash',
            OMNI: 'OmniLayer',            
            RDD: 'Reddcoin',
            UNO: 'Unobtanium',            
            VIVO: 'VIVO',
            EFL: 'E-Gulden',
            GBX: 'GoByte',
            BSD: 'Bitsend',
            LBC: 'LBRY Credits',
            ERC: 'Europecoin',
            BATA: 'Bata',
            EMC2: 'Einsteinium',
            SYS: 'Syscoin',
            IOP: 'Internet of People',
            ZEN: 'Zencash',
            XZC: 'Zcoin',
            FJC: 'Fujicoin',            
            BCBC: 'Bitcoin CBC',
            BTG: 'BitcoinGold',           
            DNR: 'Denarius',            
            FAIR: 'Faircoin',
            ARG: 'Argentum',
            LTC: 'Litecoin',
            MONA: 'Monacoin',
            NMC: 'Namecoin',
            VTC: 'Vertcoin',
            SIB: 'Sibcoin',
            BLK: 'Blackcoin',
            HUSH: 'Hush',
            SNG: 'SnowGem',
            ZCL: 'Zclassic',
            XMY: 'Myriad',
            HODLC: 'Hodl coin',
            BTX: 'Bitcore',            
            BTCZ: 'BitcoinZ',
            CHIPS: 'Chips',
            MZC: 'Mazacoin',
            ZET: 'Zetacoin',
            SLR: 'Solarcoin',
            SMLY: 'Smileycoin',            
            RBY: 'Rubycoin',
            VOX: 'RevolutionVR',
            PUT: 'PutinCoin',
            POT: 'Potcoin',
            POSW: 'Poswcoin',
            PINK: 'Pinkcoin',
            PSB: 'Pesobit',
            NSR: 'NuShares',
            NVC: 'Novacoin',
            NYC: 'NewYorkCoin',
            NRO: 'Neuro',
            LYNX: 'Lynx',
            LINX: 'Linx',
            LDCN: 'Landcoin',
            KOBO: 'Kobocoin',
            IXC: 'Ixcoin',
            INSN: 'InsaneCoin',
            THC: 'Hempcoin',
            HNC: 'Helleniccoin',
            GRC: 'Gridcoin',
            GCR: 'Global Currency Reserve',
            FRST: 'FirstCoin',
            ERC: 'Europecoin',
            EDRC: 'EDRcoin',
            ECN: 'eCoin',
            DGC: 'Digitalcoin',
            DEFC: 'Defcoin',
            CMP: 'CompCoin',
            CCN: 'Cannacoin',
            CDN: 'Canada eCoin',
            BRIT: 'BritCoin',
            XBC: 'BitcoinPlus',
            BELA: 'BelaCoin',
            USNBT: 'NuBits',
            ONX: 'Onixcoin',
            ZET: 'Zetacoin',
            JBS: 'Jumbucks',
            SLM: 'Slimcoin',
            AXE: 'Axe',            
            MZC: 'Mazacoin',
            SDC: 'ShadowCash',

        },
    },
};

export default lang;

