const lang = {
    EN: {
        API: {
            NO_UTXO_ERR: 'Нет доступных UTXO (s) или ошибка соединения',
            CANT_BROADCAST_TX_ERR: 'Невозможно транслировать транзакцию.',
            BAD_TX_INPUTS_SPENT_ERR: 'Неверные затраты на транзакции',
            CON_ERROR: 'Ошибка соединения. Пожалуйста, повторите.',
            NETWORK_ERROR_TITLE: 'Упс!!',
            NETWORK_ERROR_MSG: 'Похоже, есть некоторые проблемы с сетью, пожалуйста, убедитесь, что у вас есть подключение к интернету и попробуйте еще раз.',
        },
        SETTINGS: {
            SAVED: 'Успешно сохранены настройки',
            AUTOLOCK_TIMEOUT: 'Тайм-аут автоблокировки',
            MINUTES: 'протокол',
            SAVE: 'Сохранить',
            RECOVER: 'восстановить парольную фразу',
            RECOVER_PRIVATE_KEYS: 'ВОССТАНОВИТЬ ЗАКРЫТЫЕ КЛЮЧИ',
            LOGOUT: 'выход',
            REQUIRE_PIN_CONFIRM: 'Требовать PIN-код для подтверждения транзакции',
            ACTIVATE_WALLETS_HINT: 'Выберите кошельки, которые вы хотите активировать',
            COPIED_TO_CLIPBOARD: 'Скопировано в буфер обмена',
            REQUIRE_PASSWORD_CONFIRM: 'Требовать пароль для подтверждения транзакции',
            AUTHORIZATION_METHOD: 'Метод авторизации',
            CHANGE_PASSWORD_HINT: 'Изменить пароль',
            CHANGE_PIN_HINT: 'Изменить PIN',
            CHANGE_LANGUAGE_HINT: 'язык',
            CHANGE_CURRENCY_HINT: 'Желаемая валюта',
            REQUIRE_AUTH_CONFIRM: 'Требование авторизации для подтверждения операции',
            DISCLAIMER_MSG_ABOUT: 'Note: all FIAT quantities are approximated using external price feed sources',
        },
        RECOVERY: {
            PROVIDE_YOUR_PIN: 'Введите PIN-код для разблокировки',
            PROVIDE_YOUR_PASSWORD: 'Введите пароль для разблокировки',
            PROVIDE_YOUR_PIN_KEYS: 'Введите PIN-код для разблокировки',
            PROVIDE_YOUR_PASSWORD_KEYS: "Введите пароль для разблокировки",
            SHOW: "Шоу",
            RECOVER_WALLLET_HINT: "Используйте этот список секретных слов для получения кошелька Pungo на любом устройстве",
        },
        PIN: {
            SAVE: 'Сохранить',
            SEED_IS_ENCRYPTED: 'семя зашифрован с помощью предоставленного PIN-кода. Используйте PIN-код для входа в систему или подписания транзакции.',
            PROVIDE_A_PASSPHRASE: 'Предоставьте пароль или WIF',
            PROVIDE_A_SEED: 'Укажите посевной материал и введите 6-значный PIN-код в форме, приведенной ниже.',
        },
        OVERVIEW: {
            PRICES_ERROR: 'Поставщик цен недоступен!',
                    },
        OFFLINE: {
            TX_SIG_FAIL: 'не подписал сделку',
            CONFIRM: 'Подтвердить',
            TX_PIN_CONFIRM: 'Для подтверждения операции введите PIN-код и нажмите кнопку ниже.',
            OFFLINE_TX_SIG: 'Подписание автономных транзакций',
            SEND_FROM: 'Отправить от',
            SEND_TO: 'Отправить в',
            AMOUNT: 'Сумма',
        },
        LOGIN: {
            OR_WIF: 'или WIF',
            CREATE_A_PIN: 'Создайте штырь для входа.',
            SIGN_IN_TO_YOUR_ACC: 'Войдите в свою учетную запись Agama.',
            SIGN_IN: 'Войти',
            DONE: 'Готово',
            GENERATE: 'Генерировать',
            PASTE: 'Вставка',
            PIN_ACCESS: 'PIN-код доступа',
            WRONG_PIN: 'Неверный PIN-код!',
            LOGIN: 'Вход',
            PASSPHRASE_ACCESS: 'Пароль доступа',
            ENTER_PASSPHRASE: 'Введите парольную фразу',
            OVERRIDE_PIN: 'Создать / Заблокировать PIN-код',
            ENTER_6_DIGIT_PIN: 'Введите PIN-код (не менее 6 цифр).',
            PIN_TOO_SHORT: 'PIN-код слишком короткий!',
            I_CONFIRM_I_SAVED_SEED: 'Я подтверждаю, что сохранил семена.',
            PLEASE_MAKE_SURE_TO: 'Пожалуйста, не забудьте записать его и хранить в надежном месте!',
            THIS_IS_YOUR_NEW_SEED: 'Это твое новое семя.',
            CREATE_RECOVER_WALLET: 'Создать / восстановить кошелек',
            CONFIRMATION_REQUIRED: 'Требуется подтверждение',
            CREATE_WALLET: 'Создать кошелек',
            RECOVER_WALLET: 'Восстановить кошелек',
            PASSPHRASE_HINT: 'Вставить существующую парольную фразу или WIF',
            NEW_PIN_HINT: 'Введите новый PIN-код для доступа к вашему кошельку',
            GENERATE_NEW_PASSPHRASE_HINT: 'Сгенерировать новую парольную фразу',
            POPUP_WARNING_MSG: 'Внимание',
            POPUP_WARNING_WIPE_WALLET: 'Если вы продолжите, ваш текущий кошелек будет очищен. Ты уверен?',
            WIPE_WALLET_ACTION_YES: 'да',
            WIPE_WALLET_ACTION_NO: 'Нет',
            LOGIN_WITH_PIN_HINT: 'Представьте ваш PIN-код',
            SECURITY_ENCRYPTION_METHOD_PIN: 'PIN',
            SECURITY_ENCRYPTION_METHOD_PASSWORD: 'Пароль',
            SECURITY_ENCRYPTION_METHOD_HINT: 'Метод шифрования безопасности',
            ENTER_6_CHARS_PASSWORD: 'Введите пароль (мин. 6 символов)',
            PASSWORD_TOO_SHORT: 'Пароль слишком короткий!',
            NEW_PASSWORD_HINT: 'Введите новый пароль для доступа к вашему кошельку',
            INTRODUCE_OLD_PIN_HINT: 'Введите старый PIN-код',
            INTRODUCE_NEW_PIN_HINT: 'Введите новый PIN-код',
            CONFIRM_NEW_PIN_HINT: 'Подтвердите новый PIN-код',
            INTRODUCE_OLD_PASSWORD_HINT: 'Введите старый пароль',
            INTRODUCE_NEW_PASSWORD_HINT: 'Введите новый пароль',
            CONFIRM_NEW_PASSWORD_HINT: 'Подтвердить новый пароль',
            CONFIRM_HINT: 'Подтвердить',
            CANCEL_HINT: 'Отмена',
            PASSWORDS_DO_NOT_MATCH: 'Пароли не совпадают',
            PINS_DO_NOT_MATCH: 'PIN-коды не совпадают',
            WRONG_PASSWORD: 'Неправильный пароль!',
            ENTER_PASSWORD: 'Введите пароль',
            LOGIN_WITH_PASSWORD_HINT: 'Введите ваш пароль',
            PIN_CODES_DONT_MATCH_HINT: 'PIN-коды не совпадают',
            RE_ENTER_6_DIGIT_PIN: 'Введите PIN-код заново',
            PASSWORDS_DONT_MATCH_HINT: 'Пароли не совпадают',
            RE_ENTER_PASSWORD: 'Введите пароль еще раз',
            OPEN_WALLET: 'Открытый кошелек',
            WARNING_CREATE_WALLET_MSG: 'Создайте новый кошелек, сгенерировав новую мнемоническую фразу-пароль',
            WARNING_RECOVER_WALLET_MSG: 'Восстановите свой кошелек, вставив мнемоническую фразу-пароль',
            WARNING_MSG: 'ВНИМАНИЕ',
            WARNING_WIPE_DATA_MSG: 'Это сотрет все предыдущие данные',
        },
        SEND: {
            TOTAL: 'Всего',
            FEE: 'плата',
            BTC_FEE_SLOW: 'Медленно (60 мин)',
            BTC_FEE_AVG: 'Средний (30 мин)',
            BTC_FEE_FAST: 'Быстро (<30 мин)',
            BTC_FEES_FETCHING: 'Получение данных о гонорарах btc...',
            BTC_FEES_FETCHING_FAILED: 'Не удалось получить данные о гонорарах btc. Повторная попытка за 5 секунд ...',
            SUCCESS: 'Успех',
            TXID: 'ID транзакции',
            ENTER_YOUR_PIN: 'Введите свой PIN-код',
            ENTER_AN_ADDRESS: 'Пункт назначения',
            AMOUNT: 'Сумма',
            TO: 'Адрес назначения',
            WALLET_BALANCE: 'Баланс кошелька',
            FROM: 'От',
            BALANCE: 'Баланс',
            WARNING: 'Внимание',
            WARNING_SPV_P1: 'ваш кошелек проверен нашими выделенными серверами',
            WARNING_SPV_P2: 'Если вы все еще хотите продолжить, нажмите «Отправить».',
            SPV_VERIFYING: 'Проверка данных транзакции',
            RESULT: 'Результат',
            SUCCESS: 'успех',
            PROCESSING_SM: 'обработку...',
            PROCESSING_TX: 'Обработка транзакции...',
            ERROR: 'Ошибка',
            NAN: 'Нет номера',
            TOO_MUCH: 'Максимальная доступная сумма для отправки - @template@, чтобы исправить этот баланс и попробовать еще раз.',
            ADDRESS_IS_INCORECT: 'Адрес неверный',
            QR_SCAN_ERR: 'Невозможно декодировать QR-изображение. Пожалуйста, повторите.',
            COINS_AMOUNT_INFO_MSG: 'Количество монет меньше комиссии за транзакцию',
            ENTER_YOUR_PASSWORD: 'Введите ваш пароль',
        },
        ADD_COIN: {
            SELECT_WALLETS: 'Выберите кошельки, которые вы хотите активировать',
        },
        BALANCE: {
            BALANCE: 'Баланс',
            INTEREST: 'Награды',
        },
        DASHBOARD: {
            CON_ERROR: 'Ошибка подключения @template@. Пожалуйста, повторите попытку или подождите несколько минут.',
            SWITCH_SERVER: 'Переключатель',
            ERROR_TESTING_SERVER: 'Ошибка: сервер @template@ недоступен, повторите попытку или подождите несколько минут.',
            CONNECTING_TO_NEW_SERVER: 'Подключение к новому серверу ...',
            PROXY_ERROR: 'Прокси-сервис недоступен, попробуйте еще раз или повторите попытку.',
            RETRY: 'повторная попытка',
         },
        TRANSACTIONS: {
            UNKNOWN: 'Неизвестный',
            NO_HISTORY: 'Нет истории',
            OUT: 'Из',
            IN: 'В',
            MINE: 'Себя',
            IMMATURE: 'Взрослая',
            UNKNOWN: 'Неизвестный',
            NO_HISTORY: 'Пока нет истории tx',
            DIRECTION: 'Направление',
            CONFIRMATIONS: 'Подтверждения',
            INTEREST: 'Награды',
            TX_HASH: 'Tx hash',
            AMOUNT: 'Сумма',
            TIME: 'Время',
            COIN_ADDRESS: 'Адрес',
            },
        CLAIM: {
            WARNING: 'Предупреждение',
            WARNING_SPV_P1: 'данные вашего кошелька проверяются только одним сервером!',
            WARNING_SPV_P2: 'Если вы все еще хотите продолжить, нажмите "Подтвердить".',
            SPV_VERIFYING: 'Проверка данных транзакции',
            CONFIRM: 'Подтвердить',
            CANCEL: 'Отмена',
            FAILED_TO_CLAIM_INTEREST: 'Не удалось получить награду! Пожалуйста, повторите.',
            YOU_SUCCESFULLY_CLAIMED: 'Вы успешно заявили',
            AMOUNT: 'Сумма',
            INTEREST: 'Награды',
            INTEREST_SM: 'награды',
            LIST_SM: 'кайма',
            REQ_TO_CLAIM_P1: 'Требования к начислению вознаграждений',
            REQ_TO_CLAIM_P2: 'транзакция проведена как минимум 1 час назад, поле блокировки установлено и сумма превышает 10 KMD',
            CLAIM: 'Запрос',
        },
        APP_TITLE: {
            OVERVIEW: 'Обзор',
            SETTINGS: 'Настройки',
            RECOVERY: 'Восстановить пароль',
            'RECOVERY-KEYS': 'Восстановить приватные ключи',
            SEND: 'послать',
            ABOUT: 'О',
            CHANGE_AUTH_METHOD: 'Обновить метод автообновления',
            RECOVERY_OPTIONS: 'Варианты восстановления',
            MANAGE_COINS: 'Управлять монетами',
            LIST_OF_WALLETS: 'Список кошельков',
            'CREATE-SEED': 'Создать кошелек',
            'CREATE-RECOVER-SEED': 'Восстановить кошелек',
            'RECOVER-SEED': 'Восстановить кошелек',
        },
        COINS: {
            //supported in pungo
            PGT: 'Pungo Token',
            SMART: 'SmartCash',
            VRSC: 'Verus',
            EQLI: 'Equaliser',
            PPC: 'Peercoin',
            TPAY: 'TokenPay',
            GRS: 'Groestlcoin',
            PIVX: 'PIVX',
            XVG: 'Verge',
            OOT: 'Utrum',
            ZILLA: 'Chainzilla',
            BCH: 'BitcoinCash',
            GAME: 'GameCredits',
            XVG: 'Verge',
            SMART: 'Smartcash',
            BTC: 'Bitcoin',
            DASH: 'Dash',
            VIA: 'Viacoin',                    
            DOGE: 'Dogecoin',
            ZEC: 'Zcash',
            GRS: 'Groestlcoin',
            QTUM: 'Qtum',
            KMD: 'Komodo',
            SUQA: 'SUQA',
            PIVX: 'Pivx',
            DGB: 'DigiByte',
            EQL: 'Equaliser',
            
            // asset chains
            BET: 'BET',
            BOTS: 'BOTS',
            CEAL: 'CEAL NET',
            COQUI: 'COQUI',
            CHAIN: 'Chainmakers',
            GLXT: 'GLXToken',            
            CRYPTO: 'CRYPTO',
            HODL: 'HODL',
            DEX: 'DEX',
            JUMBLR: 'JUMBLR',
            KV: 'KV',
            MGW: 'MultiGateway',
            MVP: 'MVP Lineup',
            MNZ: 'Monaize',
            PANGEA: 'PANGEA',
            REVS: 'REVS',
            MSHARK: 'MSHARK',
            SHARK: 'SHARK',
            MESH: 'SpaceMesh',
            SUPERNET: 'SUPERNET',
            WLC: 'WIRELESS',
            AXO: 'AXO',
            ETOMIC: 'ETOMIC',
            BTCH: 'BTCH',
            BEER: 'BEER (Test coin)',
            PIZZA: 'PIZZA (Test coin)',
            VOTE2018: 'VOTE2018 (Notary Elections)',
            NINJA: 'NINJA',
            GLXT: 'GLXToken',
            BNTN: 'Blocnation',
            PRLPAY: 'Pearl Pay',
            
            // crypto
            CRW: 'Crown',
            STRAT: 'Stratis',
            TOA: 'TOA',
            USC: 'UltimateSecureCash',
            VPN: 'VpnCoin',
            WC: 'WinCoin',
            NRG: 'Energi',
            ABY: 'ArtByte',
            VOT: 'VoteCoin',
            BDL: 'Bitdeal',
            BTCP: 'BitcoinPrivate',
            MAC: 'Machinecoin',
            XWC: 'Whitecoin',
            XVC: 'Vcash',
            CRAVE: 'Crave',
            ACC: 'AdCoin',
            AC: 'AsiaCoin',
            AUR: 'Auroracoin',
            BCA: 'Bitcoin Atom',
            CLAM: 'Clams',
            CLUB: 'ClubCoin',
            DMD: 'Diamond',
            EXCL: 'ExclusiveCoin',
            FTC: 'FeatherCoin',
            FLASH: 'Flash',
            NLG: 'Gulden',
            LCC: 'Litecoin Cash',
            MNX: 'MinexCoin',
            NAV: 'NavCoin',
            NEOS: 'NeosCoin',
            OK: 'OKCash',
            OMNI: 'OmniLayer',            
            RDD: 'Reddcoin',
            UNO: 'Unobtanium',            
            VIVO: 'VIVO',
            EFL: 'E-Gulden',
            GBX: 'GoByte',
            BSD: 'Bitsend',
            LBC: 'LBRY Credits',
            ERC: 'Europecoin',
            BATA: 'Bata',
            EMC2: 'Einsteinium',
            SYS: 'Syscoin',
            IOP: 'Internet of People',
            ZEN: 'Zencash',
            XZC: 'Zcoin',
            FJC: 'Fujicoin',            
            BCBC: 'Bitcoin CBC',
            BTG: 'BitcoinGold',           
            DNR: 'Denarius',            
            FAIR: 'Faircoin',
            ARG: 'Argentum',
            LTC: 'Litecoin',
            MONA: 'Monacoin',
            NMC: 'Namecoin',
            VTC: 'Vertcoin',
            SIB: 'Sibcoin',
            BLK: 'Blackcoin',
            HUSH: 'Hush',
            SNG: 'SnowGem',
            ZCL: 'Zclassic',
            XMY: 'Myriad',
            HODLC: 'Hodl coin',
            BTX: 'Bitcore',            
            BTCZ: 'BitcoinZ',
            CHIPS: 'Chips',
            MZC: 'Mazacoin',
            ZET: 'Zetacoin',
            SLR: 'Solarcoin',
            SMLY: 'Smileycoin',            
            RBY: 'Rubycoin',
            VOX: 'RevolutionVR',
            PUT: 'PutinCoin',
            POT: 'Potcoin',
            POSW: 'Poswcoin',
            PINK: 'Pinkcoin',
            PSB: 'Pesobit',
            NSR: 'NuShares',
            NVC: 'Novacoin',
            NYC: 'NewYorkCoin',
            NRO: 'Neuro',
            LYNX: 'Lynx',
            LINX: 'Linx',
            LDCN: 'Landcoin',
            KOBO: 'Kobocoin',
            IXC: 'Ixcoin',
            INSN: 'InsaneCoin',
            THC: 'Hempcoin',
            HNC: 'Helleniccoin',
            GRC: 'Gridcoin',
            GCR: 'Global Currency Reserve',
            FRST: 'FirstCoin',
            ERC: 'Europecoin',
            EDRC: 'EDRcoin',
            ECN: 'eCoin',
            DGC: 'Digitalcoin',
            DEFC: 'Defcoin',
            CMP: 'CompCoin',
            CCN: 'Cannacoin',
            CDN: 'Canada eCoin',
            BRIT: 'BritCoin',
            XBC: 'BitcoinPlus',
            BELA: 'BelaCoin',
            USNBT: 'NuBits',
            ONX: 'Onixcoin',
            ZET: 'Zetacoin',
            JBS: 'Jumbucks',
            SLM: 'Slimcoin',
            AXE: 'Axe',            
            MZC: 'Mazacoin',
            SDC: 'ShadowCash',

        },
    },
};

export default lang;

