const lang = {
    EN: {
        API: {
            NO_UTXO_ERR: 'No available UTXO(s) or connection error',
            CANT_BROADCAST_TX_ERR: 'Can\'t broadcast transaction',
            BAD_TX_INPUTS_SPENT_ERR: 'Bad transaction inputs spent',
            CON_ERROR: 'Connection error. Please retry.',
            NETWORK_ERROR_TITLE: 'Oops!',
            NETWORK_ERROR_MSG: 'Looks like there is some network issues, please make sure you have connection to the internet and try again',
        },
        SETTINGS: {
            SAVED: 'Settings saved successfully',
            AUTOLOCK_TIMEOUT: 'Auto lock timeout',
            MINUTES: 'minutes',
            SAVE: 'Save',
            RECOVER: 'recover passphrase',
            RECOVER_PRIVATE_KEYS: 'RECOVER PRIVATE KEYS',
            LOGOUT: 'logout',
            REQUIRE_PIN_CONFIRM: 'Require PIN to confirm transaction',
            ACTIVATE_WALLETS_HINT: 'Select the wallets you want to activate',
            COPIED_TO_CLIPBOARD: 'Copied to clipboard',
            REQUIRE_PASSWORD_CONFIRM: 'Require Password to confirm transaction',
            AUTHORIZATION_METHOD: 'Authorization method',
            CHANGE_PASSWORD_HINT: 'Change password',
            CHANGE_PIN_HINT: 'Change PIN',
            CHANGE_LANGUAGE_HINT: 'Language',
            CHANGE_CURRENCY_HINT: 'Preferred currency',
            REQUIRE_AUTH_CONFIRM: 'Require authorization to confirm transaction',
            DISCLAIMER_MSG_ABOUT: 'Note: all FIAT quantities are approximated using external price feed sources',
        },
        RECOVERY: {
            PROVIDE_YOUR_PIN: 'Provide your PIN number to unlock passphrase.',
            PROVIDE_YOUR_PASSWORD: 'Provide your password number to unlock passphrase.',
            PROVIDE_YOUR_PIN_KEYS: 'Provide your PIN number to unlock private keys.',
            PROVIDE_YOUR_PASSWORD_KEYS: 'Provide your password number to unlock private keys.',
            SHOW: 'Show',
            RECOVER_WALLET_HINT: 'Use this passphrase to recover your Pungo Wallet',
        },
        PIN: {
            SAVE: 'Save',
            SEED_IS_ENCRYPTED: 'Seed is encrypted with provided PIN. Use the PIN to login or sign a transaction.',
            PROVIDE_A_PASSPHRASE: 'Provide passhprase or WIF',
            PROVIDE_A_SEED: 'Provide a seed and enter 6 digit PIN number in the form below.',
        },
        OVERVIEW: {
            PRICES_ERROR: 'Price provider is not accessible!',
                    },
        OFFLINE: {
            TX_SIG_FAIL: 'failed to sign transaction',
            CONFIRM: 'Confirm',
            TX_PIN_CONFIRM: 'To confirm transaction provide PIN and press the button below.',
            OFFLINE_TX_SIG: 'Offline Transaction Signing',
            SEND_FROM: 'Send from',
            SEND_TO: 'Send to',
            AMOUNT: 'Amount',
        },
        LOGIN: {
            OR_WIF: 'or WIF',
            CREATE_A_PIN: 'Create a pin to Sign In.',
            SIGN_IN_TO_YOUR_ACC: 'Sign In to your Agama account.',
            SIGN_IN: 'Sign In',
            DONE: 'Done',
            GENERATE: 'Generate',
            PASTE: 'Paste',
            PIN_ACCESS: 'PIN access',
            WRONG_PIN: 'Wrong PIN!',
            LOGIN: 'Login',
            PASSPHRASE_ACCESS: 'Passphrase access',
            ENTER_PASSPHRASE: 'Enter a passphrase',
            OVERRIDE_PIN: 'Create / Override PIN',
            ENTER_6_DIGIT_PIN: 'Introduce a PIN (min 6 digits)',
            PIN_TOO_SHORT: 'PIN is too short!',
            I_CONFIRM_I_SAVED_SEED: 'I confirm that I saved the seed',
            PLEASE_MAKE_SURE_TO: 'Please make sure to write it down and store in a safe place!',
            THIS_IS_YOUR_NEW_SEED: 'This is your new seed',
            CREATE_RECOVER_WALLET: 'Create / Recover Wallet',
            CONFIRMATION_REQUIRED: 'Confirmation is required',
            CREATE_WALLET: 'Create wallet',
            RECOVER_WALLET: 'Recover wallet',
            PASSPHRASE_HINT: 'Paste an existing passphrase or WIF',
            NEW_PIN_HINT: 'Introduce a new PIN to access to your wallet',
            GENERATE_NEW_PASSPHRASE_HINT: 'Generate new passphrase',
            POPUP_WARNING_MSG: 'Warning',
            POPUP_WARNING_WIPE_WALLET: 'If you proceed your current wallet will be WIPED. Are you sure?',
            WIPE_WALLET_ACTION_YES: 'Yes',
            WIPE_WALLET_ACTION_NO: 'No',
            LOGIN_WITH_PIN_HINT: 'Introduce your pin',
            SECURITY_ENCRYPTION_METHOD_PIN: 'PIN',
            SECURITY_ENCRYPTION_METHOD_PASSWORD: 'Password',
            SECURITY_ENCRYPTION_METHOD_HINT: 'Security encryption method',
            ENTER_6_CHARS_PASSWORD: 'Introduce a Password (min 6 chars)',
            PASSWORD_TOO_SHORT: 'Password is too short!',
            NEW_PASSWORD_HINT: 'Introduce a new Password to access to your wallet',
            INTRODUCE_OLD_PIN_HINT: 'Introduce old PIN',
            INTRODUCE_NEW_PIN_HINT: 'Introduce new PIN',
            CONFIRM_NEW_PIN_HINT: 'Confirm new PIN',
            INTRODUCE_OLD_PASSWORD_HINT: 'Introduce old Password',
            INTRODUCE_NEW_PASSWORD_HINT: 'Introduce new Password',
            CONFIRM_NEW_PASSWORD_HINT: 'Confirm new Password',
            CONFIRM_HINT: 'Confirm',
            CANCEL_HINT: 'Cancel',
            PASSWORDS_DO_NOT_MATCH: 'Passwords do not match',
            PINS_DO_NOT_MATCH: 'PINs do not match',
            WRONG_PASSWORD: 'Wrong Password!',
            ENTER_PASSWORD: 'Enter Password',
            LOGIN_WITH_PASSWORD_HINT: 'Introduce your password',
            PIN_CODES_DONT_MATCH_HINT: 'PIN codes don\'t match',
            RE_ENTER_6_DIGIT_PIN: 'Re-introduce PIN',
            PASSWORDS_DONT_MATCH_HINT: 'Passwords don\'t match',
            RE_ENTER_PASSWORD: 'Re-introduce Password',
            OPEN_WALLET: 'Open wallet',
            WARNING_CREATE_WALLET_MSG: 'Create a new wallet by generating a new mnemonic passphrase',
            WARNING_RECOVER_WALLET_MSG: 'Recover your wallet by inserting your mnemonic passphrase',
            WARNING_MSG: 'WARNING',
            WARNING_WIPE_DATA_MSG: 'This will wipe all previous data',
        },
        SEND: {
            TOTAL: 'Total',
            FEE: 'Fee',
            BTC_FEE_SLOW: 'Slow (60 min)',
            BTC_FEE_AVG: 'Average (30 min)',
            BTC_FEE_FAST: 'Fast (< 30 min)',
            BTC_FEES_FETCHING: 'Fetching btc fees data...',
            BTC_FEES_FETCHING_FAILED: 'Failed to retrieve btc fees data. Retrying in 5s...',
            SUCCESS: 'Success',
            TXID: 'Transaction ID',
            ENTER_YOUR_PIN: 'Enter your PIN',
            ENTER_AN_ADDRESS: 'Destination',
            AMOUNT: 'Amount',
            TO: 'Destination address',
            WALLET_BALANCE: 'Wallet balance',
            FROM: 'From',
            BALANCE: 'Balance',
            WARNING: 'Warning',
            WARNING_SPV_P1: 'your wallet tx are verified by our dedicated servers',
            WARNING_SPV_P2: 'If you still want to continue press "Send".',
            SPV_VERIFYING: 'Verifying transaction data',
            RESULT: 'Result',
            SUCCESS: 'success',
            PROCESSING_SM: 'processing...',
            PROCESSING_TX: 'Processing transaction...',
            ERROR: 'Error',
            NAN: 'Not a number',
            TOO_MUCH: 'Max. available amount to send is @template@, to fix this send balance to yourself and try again',
            ADDRESS_IS_INCORECT: 'Address is incorrect',
            QR_SCAN_ERR: 'Unable to decode QR image. Please retry.',
            COINS_AMOUNT_INFO_MSG: 'Coins amount is less than transaction fee',
            ENTER_YOUR_PASSWORD: 'Enter your Password',
        },
        ADD_COIN: {
            SELECT_WALLETS: 'Select the wallets you want to activate'
        },
        BALANCE: {
            BALANCE: 'Balance',
            INTEREST: 'Rewards',
        },
        DASHBOARD: {
            CON_ERROR: 'Connection error @template@. Please try again or wait some minutes',
            SWITCH_SERVER: 'Switch',
            ERROR_TESTING_SERVER: 'Error: server @template@ is unreachable, try again or wait some minutes',
            CONNECTING_TO_NEW_SERVER: 'Connecting to a new server...',
            PROXY_ERROR: 'Proxy service is unreachable, try again or retry',
            RETRY: 'Retry',
         },
        TRANSACTIONS: {
            UNKNOWN: 'Unknown',
            NO_HISTORY: 'No history',
            OUT: 'Out',
            IN: 'In',
            MINE: 'Myself',
            IMMATURE: 'Inmature',
            UNKNOWN: 'Unknown',
            NO_HISTORY: 'No tx history yet',
            DIRECTION: 'Dirección',
            CONFIRMATIONS: 'Confirmaciones',
            INTEREST: 'Recompensas',
            TX_HASH: 'Tx hash',
            AMOUNT: 'Amount',
            TIME: 'Time',
            COIN_ADDRESS: 'Address',
            },
        CLAIM: {
            WARNING: 'Warning',
            WARNING_SPV_P1: 'your wallet data is verified only by a single server!',
            WARNING_SPV_P2: 'If you still want to continue press "Confirm".',
            SPV_VERIFYING: 'Verifying transaction data',
            CONFIRM: 'Confirm',
            CANCEL: 'Cancel',
            FAILED_TO_CLAIM_INTEREST: 'Failed to claim rewards! Please retry.',
            YOU_SUCCESFULLY_CLAIMED: 'You succesfully claimed',
            AMOUNT: 'Amount',
            INTEREST: 'Rewards',
            INTEREST_SM: 'rewards',
            LIST_SM: 'list',
            REQ_TO_CLAIM_P1: 'Requirements to accrue rewards',
            REQ_TO_CLAIM_P2: 'spend transaction was made at least 1 hour ago, locktime field is set and amount is greater than 10 KMD',
            CLAIM: 'Claim',
        },
        APP_TITLE: {
            OVERVIEW: 'Overview',
            SETTINGS: 'Settings',
            RECOVERY: 'Recover passphrase',
            'RECOVERY-KEYS': 'Recover private keys',
            SEND: 'Send',
            ABOUT: 'About',
            CHANGE_AUTH_METHOD: 'Update auth method',
            RECOVERY_OPTIONS: 'Recovery options',
            MANAGE_COINS: 'Manage coins',
            LIST_OF_WALLETS: 'List of wallets',
            'CREATE-SEED': 'Create wallet',
            'CREATE-RECOVER-SEED': 'Recover wallet',
            'RECOVER-SEED': 'Recover wallet',
        },
        COINS: {
            //supported in pungo
            PGT: 'Pungo Token',
            SMART: 'SmartCash',
            VRSC: 'Verus',
            EQLI: 'Equaliser',
            PPC: 'Peercoin',
            TPAY: 'TokenPay',
            GRS: 'Groestlcoin',
            PIVX: 'PIVX',
            XVG: 'Verge',
            OOT: 'Utrum',
            ZILLA: 'Chainzilla',
            BCH: 'BitcoinCash',
            GAME: 'GameCredits',
            XVG: 'Verge',
            SMART: 'Smartcash',
            BTC: 'Bitcoin',
            DASH: 'Dash',
            VIA: 'Viacoin',                    
            DOGE: 'Dogecoin',
            ZEC: 'Zcash',
            GRS: 'Groestlcoin',
            QTUM: 'Qtum',
            KMD: 'Komodo',
            SUQA: 'SUQA',
            PIVX: 'Pivx',
            DGB: 'DigiByte',
            EQL: 'Equaliser',
            
            // asset chains
            BET: 'BET',
            BOTS: 'BOTS',
            CEAL: 'CEAL NET',
            COQUI: 'COQUI',
            CHAIN: 'Chainmakers',
            GLXT: 'GLXToken',            
            CRYPTO: 'CRYPTO',
            HODL: 'HODL',
            DEX: 'DEX',
            JUMBLR: 'JUMBLR',
            KV: 'KV',
            MGW: 'MultiGateway',
            MVP: 'MVP Lineup',
            MNZ: 'Monaize',
            PANGEA: 'PANGEA',
            REVS: 'REVS',
            MSHARK: 'MSHARK',
            SHARK: 'SHARK',
            MESH: 'SpaceMesh',
            SUPERNET: 'SUPERNET',
            WLC: 'WIRELESS',
            AXO: 'AXO',
            ETOMIC: 'ETOMIC',
            BTCH: 'BTCH',
            BEER: 'BEER (Test coin)',
            PIZZA: 'PIZZA (Test coin)',
            VOTE2018: 'VOTE2018 (Notary Elections)',
            NINJA: 'NINJA',
            GLXT: 'GLXToken',
            BNTN: 'Blocnation',
            PRLPAY: 'Pearl Pay',
            
            // crypto
            CRW: 'Crown',
            STRAT: 'Stratis',
            TOA: 'TOA',
            USC: 'UltimateSecureCash',
            VPN: 'VpnCoin',
            WC: 'WinCoin',
            NRG: 'Energi',
            ABY: 'ArtByte',
            VOT: 'VoteCoin',
            BDL: 'Bitdeal',
            BTCP: 'BitcoinPrivate',
            MAC: 'Machinecoin',
            XWC: 'Whitecoin',
            XVC: 'Vcash',
            CRAVE: 'Crave',
            ACC: 'AdCoin',
            AC: 'AsiaCoin',
            AUR: 'Auroracoin',
            BCA: 'Bitcoin Atom',
            CLAM: 'Clams',
            CLUB: 'ClubCoin',
            DMD: 'Diamond',
            EXCL: 'ExclusiveCoin',
            FTC: 'FeatherCoin',
            FLASH: 'Flash',
            NLG: 'Gulden',
            LCC: 'Litecoin Cash',
            MNX: 'MinexCoin',
            NAV: 'NavCoin',
            NEOS: 'NeosCoin',
            OK: 'OKCash',
            OMNI: 'OmniLayer',            
            RDD: 'Reddcoin',
            UNO: 'Unobtanium',            
            VIVO: 'VIVO',
            EFL: 'E-Gulden',
            GBX: 'GoByte',
            BSD: 'Bitsend',
            LBC: 'LBRY Credits',
            ERC: 'Europecoin',
            BATA: 'Bata',
            EMC2: 'Einsteinium',
            SYS: 'Syscoin',
            IOP: 'Internet of People',
            ZEN: 'Zencash',
            XZC: 'Zcoin',
            FJC: 'Fujicoin',            
            BCBC: 'Bitcoin CBC',
            BTG: 'BitcoinGold',           
            DNR: 'Denarius',            
            FAIR: 'Faircoin',
            ARG: 'Argentum',
            LTC: 'Litecoin',
            MONA: 'Monacoin',
            NMC: 'Namecoin',
            VTC: 'Vertcoin',
            SIB: 'Sibcoin',
            BLK: 'Blackcoin',
            HUSH: 'Hush',
            SNG: 'SnowGem',
            ZCL: 'Zclassic',
            XMY: 'Myriad',
            HODLC: 'Hodl coin',
            BTX: 'Bitcore',            
            BTCZ: 'BitcoinZ',
            CHIPS: 'Chips',
            MZC: 'Mazacoin',
            ZET: 'Zetacoin',
            SLR: 'Solarcoin',
            SMLY: 'Smileycoin',            
            RBY: 'Rubycoin',
            VOX: 'RevolutionVR',
            PUT: 'PutinCoin',
            POT: 'Potcoin',
            POSW: 'Poswcoin',
            PINK: 'Pinkcoin',
            PSB: 'Pesobit',
            NSR: 'NuShares',
            NVC: 'Novacoin',
            NYC: 'NewYorkCoin',
            NRO: 'Neuro',
            LYNX: 'Lynx',
            LINX: 'Linx',
            LDCN: 'Landcoin',
            KOBO: 'Kobocoin',
            IXC: 'Ixcoin',
            INSN: 'InsaneCoin',
            THC: 'Hempcoin',
            HNC: 'Helleniccoin',
            GRC: 'Gridcoin',
            GCR: 'Global Currency Reserve',
            FRST: 'FirstCoin',
            ERC: 'Europecoin',
            EDRC: 'EDRcoin',
            ECN: 'eCoin',
            DGC: 'Digitalcoin',
            DEFC: 'Defcoin',
            CMP: 'CompCoin',
            CCN: 'Cannacoin',
            CDN: 'Canada eCoin',
            BRIT: 'BritCoin',
            XBC: 'BitcoinPlus',
            BELA: 'BelaCoin',
            USNBT: 'NuBits',
            ONX: 'Onixcoin',
            ZET: 'Zetacoin',
            JBS: 'Jumbucks',
            SLM: 'Slimcoin',
            AXE: 'Axe',            
            MZC: 'Mazacoin',
            SDC: 'ShadowCash',

        },
    },
};

export default lang;

